### ISSUE TITLE
sdl2 - no application icon on gnome 3

### ISSUE THREAD

**Issue by fishxz** [skullernet/q2pro#102]
hey,
i recently switched to gnome 3 and noticed, that there is no icon shown, when compiled with sdl2. 

edit: i guess sdl2 missing the icon in general.

https://drive.google.com/file/d/0B-ui7VSiJnnOdlNpSUJBUm90VVk/view?usp=sharing

**Comment by PowaBanga** [comment]
Same problem on KDE

**Comment by fishxz** [comment]
you can try my flatpak build https://github.com/AndreyNazarov/q2pro/issues/111

its fixed there.

**Comment by PowaBanga** [comment]
I don't understand how to use that...
