### ISSUE TITLE
Belgian keyboard

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#110]
Hi all,
It was the same bug in yamagi, so i send the link of the issue if it can help ![yq2 issue](https://github.com/yquake2/yquake2/commit/dc155cca9cc0119461581d232654359007cdced3)

So, the problem in my cas, is that some key don't work (opensuse x86_64 42.2 leap)
When I push on 3, 5, 6, 7, (who writte ", (, §, è) on my computer ) the key just do not work.
I think that by copi/paste of this yamagi fix, the problem can be solved, but I don't find where to do that...

and more, for ponctuation, I can't write this character ingame : "?" It's realy a problem when i ask something

**Comment by fishxz** [comment]
you have to compile q2pro with sdl2 to get proper english keyboard support on non english keyboard layout. https://github.com/AndreyNazarov/q2pro/issues/66

**Comment by PowaBanga** [comment]
how to compil qpro with sdl ?

**Comment by fishxz** [comment]
copy q2pro/doc/examples/buildconfig to q2pro/.config and add "CONFIG_SDL2=y" to it.

**Comment by PowaBanga** [comment]
The good new, is that all key of my keyboard work now, but the problem that it is in qwerty at the place of azerty.
There is a way to fix that ?

**Comment by fishxz** [comment]
u cant realy fix hat, but atleast u have now a full english keyboard layout. better than before for sure...

**Comment by PowaBanga** [comment]
ok, thanks you very much, I let this issue open in the case of somebody can find a way to fix that :)

**Comment by crscum** [comment]
It is not hard to achieve better keyboard support by editing a file or two.

The relevant locations are:
1) \src\client\keys.c

2) 
a) for windows:
\src\windows\client.c

or

b) for linux:
\src\unix\sdl2\video.c   (if you used CONFIG_SDL2=y)

Just play around with the "location" of the different keys, for instance swapping y and z might be interesting for some people - or change the shifted keys, too.

Sorry, no more details (too lazy for that), but this might help you.

**Comment by skullernet** [comment]
Q2PRO uses raw keyboard scancodes on all platforms. This means scancode to `K_*` keycode table is hard-coded based on physical key location and only US qwerty layout is supported. As Quake 2 has never supported localization, there are no plans to change that. For a FPS game it is arguably more important that key bindings stay physically in place no matter what actual keyboard layout is. Closing this, if there is an issue with some keys not working, a separate issue should be opened.

**Comment by PowaBanga** [comment]
you are probably right, it's not problematic to play in quake2. What is problematic it to chat with others players ingame. It's just horrible to type any text anywhere in quake2pro if you don't remember exactly where are every keys that we need like `a` `q` `w` `z` `.` `,` `!` `:` `)`

every other players know that we play on q2pro only because of that when we speak on a q2 server, and very much times, they just don't understand what we are saying same if we speak the same language ^^

but it's ok, thank you for answer to me, and thank you very for your amazing engine, it's very nice :)

**Comment by skullernet** [comment]
Q2PRO has used logical keysyms in the past on Linux. But then people complained that it makes their keybindings keyboard layout dependent. Guess it is impossible to cover everyone's use cases.

If you compile Q2PRO yourself you can edit the keytable manually. It is in `src/unix/video/keytables/sdl.h` file for SDL2 and in `src/unix/video/keytables/evdev.c` for native X11/Wayland video drivers.

**Comment by PowaBanga** [comment]
thank you very much ! take a look on this on my todo list so ! :)
