### ISSUE TITLE
$com_maplist don't reply all my maps in q2pro.menu

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#117]
Is it normal in q2pro.menu,  `$com_maplist` don't reply a list with all my maps ?
(I have 500 maps)

**Comment by m4son** [comment]
It is probably limited to 512 or 1024 in size of a macro, meaning "test" is length for 4 and "map1 map2 map3" is length of 14 ...

**Comment by PowaBanga** [comment]
i think that I understant the stuff
