### ISSUE TITLE
Red square when map is loaded

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#118]
Hi all,
I have a red square who appear every time when I load a map. I think that it is a missing pic, but I do not know wath pic is it. Somebody can help me for that ?

On this screen, the red square is in the `N` of Cean
![](http://i.imgur.com/EIyTQnj.jpg)

**Comment by m4son** [comment]
Build q2pro with DEBUG flag and then use fs_debug 1 to see what You are missing.

**Comment by skullernet** [comment]
You can also use `imagelist -P` command to list not loaded pics referenced by server.
