### ISSUE TITLE
MacOS build ok, but launch fails

### ISSUE THREAD

**Issue by drablo** [skullernet/q2pro#122]
I know this was not mentioned in the INSTALL file (that this app actually works on mac) but I have tried to build it, successfully, however - I am missing something and the game crashes:

go@Peters-MacBook-Air-2:/Applications/Quake 2.app/Contents/Resources$ ./quake2 -framework OpenGL
------- FS_Init -------
Current search path:
./baseq2/pak2.pak (42 files)
./baseq2/pak1.pak (279 files)
./baseq2/PAK0.PAK (3307 files)
./baseq2
3628 files in PAK files
-----------------------
Execing default.cfg
Execing autoexec.cfg
Unknown command "vid_gamma"
Unknown command "gl_modulate"
------- S_Init -------
Using SDL audio driver: coreaudio
sound sampling rate: 11025
----------------------
------- R_Init -------
Using SDL video driver: Quartz
...attempting to load libGL.so.1 instead of opengl32
Couldn't load OpenGL library: Failed loading libGL.so.1: dlopen(libGL.so.1, 2): image not found
---------------------
FATAL: Couldn't initialize refresh: Couldn't load OpenGL library: Failed loading libGL.so.1: dlopen(libGL.so.1, 2): image not found
---------------------

Is this something you guys could do?

Cheers,
P.

**Comment by sthalik** [comment]
Looks like a problem with your SDL installation. Also it using the `Quartz` backend is a bad sign.
