### ISSUE TITLE
where is q2config.cfg? stored? and why overwrites all time?

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#123]
1st thing lack of settings in game u need to edit them all in config file (example s_khz) , which is overwritten all the time
2nd even if u edit  with your favourite commands for ex :   
/draw cl_fps -1 -1  // bottom right
/draw com_time 0 -1 // bottom left
/ch_scale 1.7
/cl_async 0
scr_lag_draw 1
scr_lag_x -1

noone will work from default cfg since q2pro clears it all and using some virtual 'q2config.cfg' or it overwriting it all the time...

tested on Q2PRO r1539
and Q2PRO+ r1512
------- FS_Init -------
Current search path:
C:/Users/lsd/AppData/Local/.q2online/baseq2/pak50.pkz (3 files)
C:/Users/lsd/AppData/Local/.q2online/baseq2/pak2.pak (2 files)
C:/Users/lsd/AppData/Local/.q2online/baseq2/pak1.pak (279 files)
C:/Users/lsd/AppData/Local/.q2online/baseq2/pak0.pak (3107 files)
C:/Users/lsd/AppData/Local/.q2online/baseq2
3388 files in PAK files
3 files in PKZ files
-----------------------
Execing default.cfg
Deleted all symbolic links.
Execing textures-baseq2.cfg
Execing q2config.cfg
------- R_Init -------
...enabling WGL_EXT_swap_control(_tear)
...enabling GL_EXT_compiled_vertex_array
...enabling GL_ARB_multitexture (4 TMUs)
...enabling GL_EXT_texture_filter_anisotropic (16 max)
...enabling GL_ARB_vertex_buffer_object
...enabling GL_ARB_fragment_program
----------------------
------- S_Init -------
DirectSound initialized
sound sampling rate: 44100
----------------------
Raw mouse initialized.
====== Q2PRO+ initialized ======

q2pro+ r1512~9023372, Jan  4 2016
http://skuller.net/q2pro/

**Comment by amokmen** [comment]
File 'q2config.cfg' is in your 'game' directory. Default 'game' directory is 'quake2/baseq2'. If you run your q2pro with another 'game' directory, for example 'quake2/openffa' - there would be COPY of 'q2config.cfg' which would used ONLY in this 'game'.

**Comment by tojestzart** [comment]
@amokmen  ty u gave me a patch, so i edited  in 'quake2/jump' 'q2config.cfg' and pasted those commands above - it worked! but only for 1 run, then they gone - seems i need to set config as read only

**Comment by amokmen** [comment]
No, you actually doing wrong. Normally, you should not EDIT manually 'q2config.cfg' and make 'RO'! Instead you should create your own config file, for example 'tojestzart.cfg' (could be without extensions, like 'tojestzart'). And run q2pro with THAT config: ```q2pro +exec tojestzart.cfg```

**Comment by tojestzart** [comment]
ok following your way q2pro +exec tojestzart.cfg +game jump
in game menu favourites says nothing,
except that ingame menu begins from 01 not from 00
seta adr0 "195.93.242.155:27910"
seta adr1 "195.93.242.155:27910"
im having another bug

**Comment by amokmen** [comment]
1) Read my previous message carefully. I would not help you if you even could not read.
2) If you need to connect to exact server, you just could add next to your command line: ```+connect 195.93.242.155:27910```

**Comment by sthalik** [comment]
The significance of the `seta` command as specified by @tojestzart, is it standing for "set as archive". In other words, it's gonna get set in the config file. You can use that command with arbitrary setting names.

BUT! That's not the right way to do Quake 2 configs. For years it's been:

- Create your-name.cfg, put all config stuff, including leading `unbindall`
- It should work just as well whether `q2config.cfg` exists or not
- Ignore `q2config.cfg`, known as `config.cfg` entirely
- Create `autoexec.cfg` that simply contains `exec your-name.cfg`

- - -

There are some fun stuff that wasn't (historically at least) saved. For instance

```
alias +foo "key-is-pressed-handler; other-stuff"
alias -foo "key-is-up; more-stuff"
bind z +foo
```

The scripting language is sometimes awkward to use, but it's likely turing-equivalent at that, for the geeks out there. 😆
