### ISSUE TITLE
how to change port ?

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#125]
Hi all,
I am trying to change the port of my server, and I have this error : 
```
set port 27920
port is read-only.
```
So, how to change the port of my dedied server ???

**Comment by sthalik** [comment]
It's been a while but -- pass `+set port 4242` on the command-line.

**Comment by PowaBanga** [comment]
this don't work, the port stay to 27910 when i do that.
I am on arhlinux...

**Comment by sthalik** [comment]
Set `net_port` then. It needn't be on the command-line.

**Comment by PowaBanga** [comment]
ok it work.
Thank  you very much @sthalik :)
