### ISSUE TITLE
[feature request] timestamps like in (m)irc/aprq2

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#139]
> ]aa
Q2Online: aa 
]aa
usage: connect <server>
Q2Online: aa 
]
]a
Q2Online: a 
]
]a
Q2Online: a 
]a
Flood protection:  You can't talk for 10 seconds.
couldn't exec cfg/slipmap14a.cfg
]/cl_time
   cl_timeout
   cl_timestamps
   cl_timestampsformat
]/cl_timestamps
   cl_timestamps
   cl_timestampsformat
]/cl_timestamps 1
]aa
You can't talk for 2 more seconds
]aa
You can't talk for 1 more seconds
]aa
[16:32:06] Q2Online: aa 
]/condump uaaa

> 
aprq2 1.211

**Comment by sthalik** [comment]
That's interesting. Why not even extend it to all console messages? It keeps stuff aligned with timestamps too.
