### ISSUE TITLE
crash on start, ubuntu 18.04

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#145]
Hi, I compiled Q2pro by the same way on archlinux, and ubuntu 18.04 32bit, so, the game work really good on arch, but on ubuntu 18.04, i recieve that : 

```
dbus[9881]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

what is that ? Somebody can help me to fix it ?

**Comment by skullernet** [comment]
Q2PRO doesn't use D-Bus. So this must be a bug in some other library on your system that uses D-Bus (probably SDL).
