### ISSUE TITLE
Intense overbright r1659 (windows)

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#147]
@skullernet 
can u tell me now what are defaults for gl_modulate ,  gl_modulate_entities gl_modulate_world
as before ~r1620 was gl_modulate 99?

some of maps are too bright and some too dark

[https://imgur.com/a/zg2hyCL](url) r1q2
[https://imgur.com/a/qyrDWjI](url) q2pro after updates
@sthalik 

`]\vid_restart 
------- R_Init -------
...enabling WGL_EXT_swap_control(_tear)
Detected OpenGL 4.6 (compatibility profile)
Loaded extension GL_ARB_fragment_program
Loaded extension GL_EXT_compiled_vertex_array
Using GLSL rendering backend.
----------------------
Raw mouse initialized.`

two, stop to blink entities?

**Comment by skullernet** [comment]
>q2pro after updates

Looks like `intensity` is too high. What `intensity` value are you using?

With the GLSL lighting model, `intensity` and `gl_modulate*` cvars should never be set to ridiculously high values (useful range is 1-3). If you find some parts of the map too dark, try increasing `gl_brightness` by 0.1 or so.

You can revert to old lighting model with `gl_shaders 0`.

>two, stop to blink entities?

`cl_noglow`?

**Comment by tojestzart** [comment]
works, so actual combo for SUBJECTIVE 'default' is
gl_modulate "1"
gl_modulate_entities "1" 
gl_modulate_world "1"
intensity "1"
cl_noglow "1"
gl_brightness "0.5"
works,
Regards
