### ISSUE TITLE
alt tab doesnt hide windows 10 taskbar/menu start

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#156]
as above

**Comment by tojestzart** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.
not fully privileged user

**Comment by sthalik** [comment]
Use `vid_fullscreen 1` with the desktop's resolution for a fully bordeless mode. You have fullscreen disabled and are clicking outside the window on a sharp move to the side.
