### ISSUE TITLE
ignorenick & ignoretext doesnt work with Action mod

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#166]
It looks like

> [DEAD] noob: foo
> [DEAD] (noob): bar

https://github.com/skullernet/q2pro/blob/0604b7f502b47305161e42907a077c4435a7f807/src/client/main.c#L1995

**Comment by skullernet** [comment]
`ignoretext` adds a generic filter, it should work with any mod that generates PRINT_CHAT messages. As for `ignorenick`, it's just convenience wrapper over `ignoretext`. You can try to emulate it with custom alias: `alias myignorenick "ignoretext ${qt}[DEAD] ${1}: *${qt}; ignoretext ${qt}[DEAD] (${1}): *${qt}"`. This has a downside though, if nickname has special characters in it, they need to be escaped.

**Comment by m4son** [comment]
Your proposed custom alias works. never thought about it though since wiki/readme does not say nothing about it. One downside is also nick completion, since it's `ignoretext` it does not work and user experience is mixed ;)
