### ISSUE TITLE
[Feature Request]: IPv6 Support for Q2Pro

### ISSUE THREAD

**Issue by MasterO2** [skullernet/q2pro#167]
I am requesting that IPv6 support be added to Q2Pro.  

I know that IVP6's implementation is fairly new in the networking world in general. However, since the internet is going to be running IPv4 and IPv6 for the foreseeable future, I believe it would make sense to start implementing IPV6 now to avoid obvious future connectivity problems.

**Comment by sthalik** [comment]
The issue is moot since ipv6 is already supported by q2pro. Enable as per user docs and surround numeric addresses in square brackets.

**Comment by MasterO2** [comment]
> The issue is moot since ipv6 is already supported by q2pro. Enable as per user docs and surround numeric addresses in square brackets.

Oh I was not aware that had been changed. Thank you for clarifying. You can close this issue then.
