### ISSUE TITLE
facing in wrong direction when leaving teleport in some cases

### ISSUE THREAD

**Issue by fishxz** [skullernet/q2pro#173]
hey,
in some cases, the game faces in wrong direction, when leaving teleporter, i was able to reproduce this on both baseq2 and jump mod, running on q2proded.

i think it has to do with, how you enter the teleporter, because i made a teleport loop map, where i got teleported without pressing a key and there it never happened.

i attached the testmap and the demo, which shows the problem. the bug happens to the end of this demo.

[telebug.zip](https://github.com/skullernet/q2pro/files/2567541/telebug.zip)

**Comment by sthalik** [comment]
@fishxz It's more likely some singularity in trig rather than uninitialized memory. Normally I'd suggest running Valgrind on the dedicated server but it's probably just wasted effort.

**Comment by skullernet** [comment]
Can you test this patch?
```
--- a/src/client/input.c
+++ b/src/client/input.c
@@ -583,21 +583,18 @@ static void CL_ClampSpeed(vec3_t move)
 
 static void CL_ClampPitch(void)
 {
-    float pitch;
+    float pitch, angle;
 
     pitch = SHORT2ANGLE(cl.frame.ps.pmove.delta_angles[PITCH]);
-    if (pitch > 180)
-        pitch -= 360;
-
-    if (cl.viewangles[PITCH] + pitch < -360)
-        cl.viewangles[PITCH] += 360; // wrapped
-    if (cl.viewangles[PITCH] + pitch > 360)
-        cl.viewangles[PITCH] -= 360; // wrapped
-
-    if (cl.viewangles[PITCH] + pitch > 89)
-        cl.viewangles[PITCH] = 89 - pitch;
-    if (cl.viewangles[PITCH] + pitch < -89)
-        cl.viewangles[PITCH] = -89 - pitch;
+    angle = cl.viewangles[PITCH] + pitch;
+
+    if (angle < -180)
+        angle += 360; // wrapped
+    if (angle > 180)
+        angle -= 360; // wrapped
+
+    clamp(angle, -89, 89);
+    cl.viewangles[PITCH] = angle - pitch;
 }
```

**Comment by fishxz** [comment]
i tested quite a while and i cant reproduce the bug anymore with your patch, so i assume it is fine.

**Comment by skullernet** [comment]
Nice, thanks.
