### ISSUE TITLE
Question about  'Allow built-in menus to be overridden'

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#174]
Commit [261f9ae](https://github.com/skullernet/q2pro/commit/261f9ae2389443f26732232cc84fbaec6030e11b) says I can override built-in menus. 
Something does not work for me or I am doing something wrong. 
How do I set background image to these three menus since this commit they are black, they do not get background information from the .menu configuration

**Comment by skullernet** [comment]
I forgot that q2pro.menu needs to be loaded first to set up default background, etc. Reverted that commit for now.
