### ISSUE TITLE
Kubuntu 18.10 - bind ESCAPE "togglemenu"

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#179]
Doesnt work ?
ps. doesnt matter how long im pressing it
nouveau in use

**Comment by skullernet** [comment]
This is by design. ESCAPE key is hard coded, so the user can never unbind it (or bind to different action for that matter).

**Comment by tojestzart** [comment]
skuller i dont want to waste your time for 'minor' issues, bind escape "pushmenu main" its same with togglemenu, but it doesnt call 'main' game options, i think its related to kde environment/wayland so closing that.

**Comment by tojestzart** [comment]
Regards
