### ISSUE TITLE
Problem loading MD3 textures/skins?

### ISSUE THREAD

**Issue by protox** [skullernet/q2pro#189]
Exporting MD3 models from Blender 2.79 using MD3 script (https://www.katsbits.com/tools/#md3). Model and animations work, however importing skin/texture tosses an error either filename too short or incorrect quake path. I've tried like a dozen ways to attach a texture. Any ideas?

Is there like an example blender file somewhere?

Thank you

**Comment by protox** [comment]
Nevermind I got it working with Misfit Model 3D, this isn't the fault of Q2Pro it's just not well documented how textures need to be loaded for MD3s.

If you open your MD3 file in Misfit Model 3D and go to Model > Edit Model Meta Data you can set the MD3_PATH, for the AQ2 v_knife model I simply put models/weapons/v_knife, skin now loads.

**Comment by skullernet** [comment]
I don't know anything about MD3 exporting tools. But they probably assume Quake 3 engine. MD3 models in Q2PRO are used as one to one replacements for MD2 models. Q2PRO does not support Quake 3 engine features like shaders, tags, etc. It simply loads all the meshes and their skins. When loading skins it just uses the skin path stored in MD3 verbatim. It must be non-empty and have a known extension at the end (.pcx, .tga, .png or .jpg).
