### ISSUE TITLE
cl_timenudge?

### ISSUE THREAD

**Issue by quaker2** [skullernet/q2pro#191]
Привет Андей. Поииграл в ку3 и игра на равных пингах реагирует на нажатие на много быстрее чем ку2. Даже если не использовать нудге. В ку2 можно что поправить что бы игра откликалась быстрее?

**Comment by quaker2** [comment]
импутлаг в ку2 есть серьезный особенно если с gl стрелять. особенно в движении

**Comment by skullernet** [comment]
Такого параметра нет. Есть sv_fps, но его поддержка по умолчанию в бинарных сборках выключена, и он работает не со всеми модами. Можно считать, что задержка в Q2 является особенностью игры (нужно уметь стрелять на упреждение), и если ее менять, игровой баланс будет нарушен. Поэтому подобные изменения в Q2 не приветствуются.
