### ISSUE TITLE
[bug] Q2PRO Unhandled Exception in Win10 after game quit if OpenAL was choosen

### ISSUE THREAD

**Issue by amokmen** [skullernet/q2pro#192]
## Environment
* Windows 10 x64 10.0.16299.125
* Q2PRO r1504\~924ff39 or r1844\~51bdb22
* OpenAL Soft Binary Distribution 1.20.0

## Reproducing
1. Rename _soft_oal.dll_ to _OpenAL32.dll_ and put DLL into `..\q2pro\` directory (according OpenAL readme file).
2. Run Q2PRO.
3. Choose in sound settings "OpenAL".
4. Check in console message that there is no errors and OpenAL was choosed.
5. Quit from game by input in console "quit".
6. Exception occurs (see screenshot).

## Screenshots and logs
![image](https://user-images.githubusercontent.com/10855248/71471516-b6211380-27e0-11ea-9049-4f4d5967ab1d.png)

[Crash report here](https://gist.github.com/amokmen/21aee696711a3e3355162d24112e25fe)

**Comment by skullernet** [comment]
Not Q2PRO bug, but rather an issue with how 32-bit soft_oal.dll is built upstream. Even openal-info.exe from their binary distribution crashes on exit. 64-bit version should work fine.

**Comment by amokmen** [comment]
Actually, I am almost sure that I used 64 bit version of DLL.
Both 64/32 bit versions should be renamed to _OpenAL**32**.dll_.

**Comment by skullernet** [comment]
But the crash report is from 32-bit q2pro.exe. 32-bit processes can't load 64-bit DLLs.

**Comment by amokmen** [comment]
Yeap, my bad. Yes, q2pro could not load 64bit openal DLL.

Btw, just checked openal-soft-**1.20.1** 32bit DLL - problem is still here.

**Comment by skullernet** [comment]
Reported the crash [here](https://github.com/kcat/openal-soft/issues/394).
