### ISSUE TITLE
Q2PRO switches to Windows Desktop while trying to do rocketjump (mouse down + attack)

### ISSUE THREAD

**Issue by amokmen** [skullernet/q2pro#193]
## Environment
* Win 10 x64
* Dual monitor configuration (4K + 2K)
* Q2PRO r1844\~51bdb22

## What's happening
1. Run Q2PRO in fullscreen on 4K main monitor.
2. `map q2dm1`
2. Do **fast move down with mouse** to watch at ground **and press attack** (it's like you manually want to do rocketjump). Actually I could do same with moving to left and right with attacking at the move end - but this is harder to reproduce.
3. Q2PRO would be switched to Windows Desktop like I pressed "Alt+TAB".

**Comment by skullernet** [comment]
Can't reproduce.

**Comment by amokmen** [comment]
Could not reproduce now too.
