### ISSUE TITLE
Local server has sv_paused always set to "1"

### ISSUE THREAD

**Issue by pokeshark** [skullernet/q2pro#199]
I use "+set sv_paused 0" in command line, also my config contains sv_paused "0"
But when launching a map and accessing the console, the game is paused.

When I check in console current sv_paused value, it is set to "1".
https://i.imgur.com/TYShbBm.png

**Comment by tojestzart** [comment]
in Server settitngs or in which commandline? that might be also mod failure which is listening client command

**Comment by pokeshark** [comment]
I have made a .bat to launch the game:
q2pro.exe +set deathmatch 1 +sv_paused "0" +set sv_paused "0" +gamemap q2dm1

also did a clean install with only original .pak's and latest Q2Pro client: https://skuller.net/q2pro/nightly/q2pro-client_win32_x86.zip but the issue persists

**Comment by jar3817** [comment]
Your not loading the map, which is why it's paused. "gamemap" isn't a cvar
or command, it's just "map". Try this command to see if it works:

q2pro.exe +set deathmatch 1 +map q2dm1

You can also probably just type "map q2dm1" in the paused server once you
start it with the command you're using.

**Comment by pokeshark** [comment]
I used: q2pro.exe +set deathmatch 1 +map q2dm1 and issue with pause still occurs

as an independent check, I used an old aprq2.exe client with the clean install and above command line args and you can't pause in deathmatch. this client doesn't even have the sv_paused variable to begin with.

**Comment by m4son** [comment]
> **cl_autopause**
> _Specifies_ if single player game or demo playback is automatically paused once client console or menu is opened. **Default** value is **1** (pause game).

**Comment by pokeshark** [comment]
that was it. thank you very much!

sorry for the noob question.
