### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by PRinceBhai** [skullernet/q2pro#200]
1. Add a option to adjust dynamic light intensity and resolution (For older hardware)
2. View-model Fov, if possible please add this. I play on (1280x600) and the view-models are cranked under the screen
3. Add `bind "previous weapon" weapprev` under `begin keys` in q2pro.menu
4. Add    `
blank
action "load last Quick Save..." "load quick"
blank
`
under `begin loadgame` and `	blank
	action "Save On Quick Save Slot..." "save quick"
    blank` under `begin savegame` If it seems fit, in q2pro.menu (There is supposed to be a "enter" (\n) after the "blank" dunno why it didn't work in the editor. )

This is literally the best source port.
I hope these might be considered.

**Comment by skullernet** [comment]
1. Dynamic light resolution is fixed at lightmap resolution. It cannot be changed without adopting different map format. As for dynamic light intensity, `gl_dlight_falloff` variable can influence it to some extent.
2. If you mean gun model fov, it was implemented in 8fef9dde.
3. Implemented in d0878e21.
4. I've tried to add these items and they really look out of place. Quick save first and foremost is for quick access from keyboard, I don't think it really belongs to savegame menu.
