### ISSUE TITLE
strange/buggy minimize behavior on linux

### ISSUE THREAD

**Issue by fishxz** [skullernet/q2pro#202]
q2pro has a strange minimize behavior on linux (tested on gnome desktop).

when minimize via ALT+TAB the game goes into a small windows mode and cuts of the content of the screen.

![image](https://user-images.githubusercontent.com/1385258/88455970-40fee500-ce7a-11ea-9095-d5c0bac517f3.png)

when minimize via WINDOWS KEY the window is completly buggy.

![image](https://user-images.githubusercontent.com/1385258/88455952-190f8180-ce7a-11ea-9d18-cb635cc52c10.png)

is the game supposed to go into windows mode when minimized (you can noticed on the border that its no longer in fullscreen)

**Comment by amokmen** [comment]
Read this my [comment](https://github.com/skullernet/q2pro/issues/188#issuecomment-569027659).

**Comment by skullernet** [comment]
This bug report needs more information. What distribution is this, whether it uses X11 or Wayland, etc.

**Comment by fishxz** [comment]
fedora+wayland

**Comment by tojestzart** [comment]
I have "similar" problem i cant minimize q2pro properly r1881, not sure its KDE fault or q2pro. its overlaying my wallpapper when trying to minimize.
![Uploading Screenshot_20210916_143001.png…]()
