### ISSUE TITLE
Game does not support enhanced savegames (The Reckoning Mission Pack)

### ISSUE THREAD

**Issue by spamzilla** [skullernet/q2pro#203]
Well, I just finished normal Quake 2 without a flaw. So I figured that I would play the mission packs. The Reckoning seems to work fine as well until I try to save and come across this message :  "Game does not support enhanced savegames". Is there something I can do about this? I can't play the mission pack without it!

**Comment by amokmen** [comment]
**q2pro** mostly multi-playing client, for better single-playing you probably should use https://yamagi.org/quake2/

**Comment by skullernet** [comment]
Q2PRO refuses to load/save games unless game .dll/.so advertises `GMF_ENHANCED_SAVEGAMES` bit in `g_features` cvar. This is to prevent users from accidentally running original (broken) savegame code and crashing Q2PRO. Other than that, Q2PRO doesn't impose any restrictions on whatever internal savegame format particular game .dll/.so uses, provided it's stable enough. Thus, you can enable savegames in Q2PRO with mission pack sources from Yamagi Q2 (which have savegame system rewritten/fixed) if you patch their `InitGame` function like this:

```
--- a/src/savegame/savegame.c
+++ b/src/savegame/savegame.c
@@ -254,6 +254,9 @@ InitGame(void)
        /* items */
        InitItems ();

+       /* enhanced savegames */
+       gi.cvar_forceset("g_features", "1024");
+
        game.helpmessage1[0] = 0;
        game.helpmessage2[0] = 0;
```
