### ISSUE TITLE
Using symbolic link or renaming executable causes Fatal Error (Windows)

### ISSUE THREAD

**Issue by Kormann** [skullernet/q2pro#207]
I wanted to use Q2Pro on Steam and I get the error "Couldn't initialize refresh: Unsupported OpenGL version/profile". It also happens if I try to run the symbolic link, hardlink or renamed .EXE from the Quake 2 folder.

![q2pro-fatalerror](https://user-images.githubusercontent.com/8125662/108203772-b9244500-7101-11eb-9208-48fb090e6800.jpg)

EDIT: I tested again and it can be renamed to anything but quake2.exe. Because of that there's no way to replace quake2 steam executable by q2pro and so the player can't contribute to Steam Quake 2 Statistics.

**Comment by Kormann** [comment]
I tested again and it only happens when the EXE is renamed to quake2.exe or when I create a symbolic link as quake2.exe. It can be renamed to anything but quake2.exe
Because of that there's no way to replace quake2.exe from steam with this. It's bad because we can't contribute to quake2 statistics over steam.

**Comment by Kormann** [comment]
I was investigating the source code and I thought that it was related to
src\client\refresh.c
src\client\qgl.c

In **qql.c** the QGL_Init starts and checks GL version and if it doesn't meet the requirements prints an error message and the Fatal Error happens.

From line 530 trought the end of the file is where the Fatal Errors checks occur.

```
    if (gl_config.ver_es) {
        if (gl_config.ver_es < 30 || gl_config.ver_sl < 300)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & (QGL_CAP_LEGACY | QGL_CAP_SHADER))) {
            Com_EPrintf("Unsupported OpenGL ES version\n");
            return false;
        }
    } else {
        if (gl_config.ver_gl < 30 || gl_config.ver_sl < 130)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & QGL_CAP_LEGACY)) {
            Com_EPrintf("Unsupported OpenGL version/profile\n");
            return false;
        }
    }
```

The Fatal Error **"Couldn't initialize refresh: Unsupported OpenGL version/profile"** code starts at 529, it checks the GL version if it's below 3.0 and if the GLSL version is below 1.30. And in line 533 is where I located the error message.

```
        if (gl_config.ver_gl < 30 || gl_config.ver_sl < 130)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & QGL_CAP_LEGACY)) {
            Com_EPrintf("Unsupported OpenGL version/profile\n");
            return false;
        }
```
So I analyzed the previous Fatal Error and I starred at the line 524. I thought that the line 532 was incomplete and missed something.
So now I copied the line 524 to 532. So the **Unsupported OpenGL version/profile** Fatal error code was changed to this:

```
        if (gl_config.ver_gl < 30 || gl_config.ver_sl < 130)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & (QGL_CAP_LEGACY | QGL_CAP_SHADER))) {
            Com_EPrintf("Unsupported OpenGL version/profile\n");
            return false;
        }
```

And all Fatal Error checks after the "fix":

```
    if (gl_config.ver_es) {
        if (gl_config.ver_es < 30 || gl_config.ver_sl < 300)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & (QGL_CAP_LEGACY | QGL_CAP_SHADER))) {
            Com_EPrintf("Unsupported OpenGL ES version\n");
            return false;
        }
    } else {
        if (gl_config.ver_gl < 30 || gl_config.ver_sl < 130)
            gl_config.caps &= ~QGL_CAP_SHADER;

        if (!(gl_config.caps & (QGL_CAP_LEGACY | QGL_CAP_SHADER))) {
            Com_EPrintf("Unsupported OpenGL version/profile\n");
            return false;
        }
    }
```

**Now it's possible to rename Q2PRO.EXE to QUAKE2.EXE.**

After renaming the executable to QUAKE2.EXE, the game loads normally but you can't change GL_SHADERS to 0. It's only 1. So the Legacy rendering backend is not available.
The curious thing is if I rename QUAKE2.EXE back to Q2PRO.EXE I can change GL_SHADERS from 0 to 1 and vice-versa and all backend rendering works Legacy or GLSL.

I don't know if this change is an ugly fix but it worked.
Any thoughts?

**Comment by Kormann** [comment]
### Real problem
I investigated more about this issue and the real problem lies in NVIDIA driver patching the quake2.exe with it's profile fix.

Because of that the renamed q2pro.exe (to quake2.exe) is receiving the NVIDIA patch and then it's breaking the game and triggering the Fatal Error from qgl.c. If I disable NVIDIA extension limit quake2.exe patch the game works without errors. So the real solution would be ignore NVIDIA patch for q2pro's "quake2.exe".

![nvidia-profile-inspector-quake2](https://user-images.githubusercontent.com/8125662/110151941-d9215d00-7dbf-11eb-802c-f18c38f2066a.jpg)

### Ideal solution
To create this solution we don't need to rename q2pro.exe, we need to create an executable wrapper (quake2.exe) that would redirect to q2pro.exe, including launch options like "+set game ...".

I discovered that [Yamagi Quake II](https://github.com/yquake2/yquake2) fixed the same problem with [this solution](https://github.com/yquake2/yquake2/blob/master/src/win-wrapper/wrapper.c), creating a quake2.exe wrapper and including it alongside it's executable in each release.

So I adapted the code and compiled myself with q2pro. It worked perfectly. It's now possible unzip q2pro in Quake II Steam folder and replace the original quake2.exe with the wrapper. It also loads any launch options.

**Comment by skullernet** [comment]
Even in shader mode, Q2PRO needs compatibility OpenGL context because it uses features removed in desktop OpenGL 3.2+ such as client side vertex arrays. Hence the check for `QGL_CAP_LEGACY` bit at line 532. These features are still supported in OpenGL ES, hence the check for `QGL_CAP_LEGACY | QGL_CAP_SHADER` at line 524.

Due to NVIDIA driver interference `GL_ARB_compatibility` extension is likely lost due to extension string limiting if executable is renamed to quake2.exe, hence the error (though wtf, if OpenGL version is 3.0+, Q2PRO doesn't even parse extension string and uses `glGetStringi` instead). So, strictly speaking, not Q2PRO issue, but graphics drivers being too "smart".
