### ISSUE TITLE
Changes to fix Windows compilation & cvar improvements

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#212]
Fixes Windows compilation on modern MSVC-based compilers, and also changes some cvars to archive so we don't have to keep modifying configs.

Change list here:
https://github.com/q2wasm/q2pro/commit/597d61b6a9c9f89363535718c8ebb0b79f30a0f9

**Comment by skullernet** [comment]
I've addressed some of these problems, except:
* Negating of unsigned integers is legal, compiler warning (if any) is false positive and should be disabled.
* Cvars modified via menus are already automatically archived, no need to add `CVAR_ARCHIVE` flag manually.
