### ISSUE TITLE
Cannot select OpenAL sound engine

### ISSUE THREAD

**Issue by miquecg** [skullernet/q2pro#214]
Hi,

I've compiled q2pro with OpenAL support but I don't manage to get it selected. Sound works on the game, I can hear the effects, but the menu says that sound engine is `software`.

These are the relevant compilation flags:
```
# Enable OpenAL sound engine.
CONFIG_OPENAL=y

# Enable direct sound driver (DirectSound on Windows, OSS on Linux). This
# option has no effect if CONFIG_NO_SOFTWARE_SOUND is set.
#CONFIG_DIRECT_SOUND=y

# Disable default Quake 2 software sound engine. Only makes sense when
# CONFIG_OPENAL is set.
CONFIG_NO_SOFTWARE_SOUND=y
```

In my personal config file I've set `s_enable "2"`, which corresponds to OpenAL, but on console I can check that it was reverted: `"s_enable" is "1"`. No matter if I change it through game menu either.
```
------- FS_Init -------
Current search path:
./baseq2/pak99_textures.pak (1820 files)
./baseq2/pak98_pics.pak (58 files)
./baseq2/pak97_models_bright.pak (135 files)
./baseq2/pak97_models.pak (123 files)
./baseq2/pak95_v_models.pak (27 files)
./baseq2/pak2.pak (2 files)
./baseq2/pak1.pak (279 files)
./baseq2/pak0.pak (3307 files)
./baseq2
5751 files in PAK files
-----------------------
Execing default.cfg
Execing config.cfg
Execing autoexec.cfg
Execing custom.cfg
------- S_Init -------
OpenAL initialized.
----------------------
------- R_Init -------
Detected OpenGL 4.6 (compatibility profile)
Loaded extension GL_ARB_fragment_program
Loaded extension GL_EXT_compiled_vertex_array
Using GLSL rendering backend.
----------------------
SDL mouse initialized.
====== Q2PRO initialized ======

q2pro r1862~4e94673, Apr 18 2021
https://github.com/skullernet/q2pro

Shutting down OpenAL.
```

`"al_driver" is "libopenal.so.1"` which is installed on my system:
```
$ pacman -Ql openal | grep libopenal.so
openal /usr/lib/libopenal.so
openal /usr/lib/libopenal.so.1
openal /usr/lib/libopenal.so.1.21.1
```

**Comment by skullernet** [comment]
This is by design. `s_enable` is essentially a sound backend number (with 0 being sound disabled). By disabling legacy sound backend at compile time, OpenAL becomes sound backend number 1. It even says in your console that OpenAL has been successfully initialized. The menu script simply doesn't account for that.

**Comment by ocelot77** [comment]
I can't get OpenAL sound working. I have OpenAL installed and it works in Yamagi Quake - I even tried copying openal32.dll from Yamagi to Q2PRO, but that didn't help - any tips? 
Thank you
