### ISSUE TITLE
how to print all console text in a log file ?

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#215]
Hi,
i run quake2pro in debug mode, (fs_debug 1) and i have very much text who can be easiest to manipulate if they are in file.
but, when i run it in a console like this : 
```
q2pro > logfile.log 2>&1
```
the file output is just empty... :/

Does anybody know a way to put all log in a text file ?

**Comment by jar3817** [comment]
Use the `condump [filename]` command to save everything in the console to a file.

**Comment by PowaBanga** [comment]
ha yeah, thank you very much !
