### ISSUE TITLE
fix muzzleflash lighting?

### ISSUE THREAD

**Issue by xboxownzuall** [skullernet/q2pro#221]
When i shoot the machine gun or chain gun with v sync off it's just a yellow line across the screen it doesnt render correctly with v sync off like 3.20 or 3.24 does with v sync off, is there a way to fix this besides using v sync which introduces mouse lag? I tried capping the framerate and it doesnt resolve the issue like capping framerate in yamagi does.

**Comment by Paril** [comment]
Muzzleflashes in Q2PRO only last for a single frame, whereas in most other clients they last for a small amount of time. I'm not sure if Skuller is interested in the fix for this but I do have it laying around somewhere..

**Comment by vic7or777** [comment]
where to get binaries with this fix?
only r1897 at https://skuller.net/q2pro/nightly/

**Comment by skullernet** [comment]
Nightly builds should include the fix now.
