### ISSUE TITLE
Case sensitive problem with textures

### ISSUE THREAD

**Issue by PowaBanga** [skullernet/q2pro#223]
Hello

There is a lot of map who are looking for same files with different case like
```
texture/e1u1/file.wal
texture/E1U1/File.wal
texture/E1U1/file.wal
texture/e1u1/FILE.wal
...
```
so q2pro consider just that the file is does not exist...
is it a way to do in sort that q2pro will be insensitive to the case to load texture ? To look systematically for the file in lower case for exemple ?

**Comment by Paril** [comment]
Q2's VFS is supposed to be case-insensitive so I'd probably consider this a bug, yeah.

**Comment by skullernet** [comment]
I don't understand what bug is reported here. What has been tried and what exactly doesn't work?

Q2 VFS is case insensitive, matching files in packfiles is case insensitive as well. Of course, when actual filesystem Q2PRO runs from is case sensitive, mixed case paths can become a problem. On non-Windows platforms, when Q2PRO tries to load a file with upper case letters in name from disk, it will first try the filename verbatim, and if that fails with ENOENT error, it will convert filename to lower case and retry.

Also when requesting downloads from server all paths are converted to lower case.

**Comment by skullernet** [comment]
No response, closing.
