### ISSUE TITLE
Thirdperson on multiplayer server

### ISSUE THREAD

**Issue by Noctisq2** [skullernet/q2pro#225]
theres any option to be able to open this feature? i curretly see the thirdperson gameplay quite interesting experience for new and old players.

**Comment by joe0x04** [comment]
This is mod-specific rather than something the server does.

**Comment by Noctisq2** [comment]
> This is mod-specific rather than something the server does.

i had tried the thirdperson on EGL Client(the best one so far),KMQuake2, some thirdperson with dll, and i know this feature can be used on q2pro but u say its only server side? then how i can use it from other clients? on the same server, just want to know  if theres any chance.

**Comment by Bad-ptr** [comment]
cl_thirdperson 1
cl_thirdperson is cheat protected

**Comment by Noctisq2** [comment]
> 

damn, so.. 0 chances ? i wanted to make some trailers for quake2 and attract people with thirdperson/firstperson gameplay on the best client (q2pro)

**Comment by m4son** [comment]
Record a demo and watch it with cl_thirdperson later...

**Comment by skullernet** [comment]
`cl_thirdperson` is cheat protected for a reason: it is possible to abuse it to look behind corners, which is unfair advantage in competitive play. You can still enable it in single player or during demo playback.
