### ISSUE TITLE
Discord GameSDK

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#229]
Hello,

I was looking at what it would take to get the Discord GameSDK enabled for Q2Pro to have Discord Presence, joining games from Discord and other features?  Would this be something you'd be interested in adding, even as an option in the .config when compiling?

https://discord.com/developers/docs/game-sdk/sdk-starter-guide

**Comment by darkshade9** [comment]
This may have GPL licensing considerations, we may need something like a shim to make sure something like this doesn't break the GPL

**Comment by ndit-dev** [comment]
https://github.com/skullernet/q2pro/compare/master...ReKTeK:q2pro:discord

**Comment by skullernet** [comment]
Linking with proprietary code like that can be considered GPL violation. And Discord (and similar fringe third-party stuff) integration is not something I'd like to have in Q2PRO in general.
