### ISSUE TITLE
Why is not autoexec, postexec and postinit allowed in pak-files?

### ISSUE THREAD

**Issue by ndit-dev** [skullernet/q2pro#237]
How come `autoexec`, `postexec` and `postinit` is not allowed to be executed at start if it placed in a pak-file?
https://github.com/skullernet/q2pro/blob/master/src/common/common.c#L982
I am considering patching that in a fork, but would like to know if there is any technical reason for doing it like it is done right now

**Comment by skullernet** [comment]
This files are supposed to be user-editable, which means they must be real files within the game directory. If a packfile overrides them changes made by user to these files will have no effect.
