### ISSUE TITLE
no menu when pressing escape on GTV server

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#239]
Escape button doesn't open q2pro menu on GTV server. 
Works if pushmenu is binded to anything else than escape.

**Comment by skullernet** [comment]
You need to hold Esc key to force open in-game menu. Normally when scoreboard/inventory layout is present Esc closes the layout first by sending `putaway` command to server. But on MVD/GTV server there is always forced layout present which cannot be closed.
