### ISSUE TITLE
muzzleflash saturation

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#251]
As is gl_saturation 0 affects global lights basically for everything. Would it make sense to exempt saturation on muzzleflashes?

**Comment by skullernet** [comment]
`gl_saturation` only affects textures. Do you mean `gl_coloredlightmaps`? Due the way blocklights conversion is implemented (mix all lightmaps and dynamic lights first, then normalize/desaturate), it is not practical to exempt certain kinds of lights like muzzleflashes from this.
