### ISSUE TITLE
GMF_CLIENTNUM feature request

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#260]
GMF_CLIENTNUM works perfectly with non-client entities in R1Q2's server code, however Q2PRO seems to have an issue when switching `clientNum` between certain non-client entities.
Per the R1Q2 [comment in the source code](https://github.com/tastyspleen/r1q2-archive/blob/master/server/server.h#L794), the clientNum does not necessarily specify the entity number of a client, but an entity number to be hidden from the client.
```
// server is able to read clientNum field from gclient_s struct and hide appropriate entity from client
// game DLL fills clientNum with useful information (current POV index)
#define GMF_CLIENTNUM   1
```

Q2PRO seems to have issues when switching between certain non-client entities which I suspect may have something to do with [this deduction](https://github.com/skullernet/q2pro/blob/master/src/server/entities.c#L99), though admittedly I have not taken the time to analyze it thoroughly. The effect in-game is that it shows the model after certain entity switches. To reiterate, these entity numbers are greater than "maxclients" and the switching is not necessarily in numeric entity order.

Could this be fixed?

**Comment by Paril** [comment]
It seems like R1Q2 only used clientNum to hide an entity, and nothing more; I believe Q2PRO actually takes it a step farther and assumes on both ends that the clientNum will equal the entity that is client-side, which allows for things like demos that switch views to appear smooth (the clientNum is actually sent to the client so it knows which index it is; this is bounded by MAX_CLIENTS/sent as a byte).

I guess nobody had used clientNum on a non-player entity when this was implemented initially.

**Comment by ThePhatman** [comment]
> It seems like R1Q2 only used clientNum to hide an entity, and nothing more; I believe Q2PRO actually takes it a step farther and assumes on both ends that the clientNum will equal the entity that is client-side, which allows for things like demos that switch views to appear smooth (the clientNum is actually sent to the client so it knows which index it is; this is bounded by MAX_CLIENTS/sent as a byte).
> 
> clientNum is set to a client index (which always equals entity number - 1) so I think this indicates that R1CH only ever thought it was going to reference valid client indexes. The fact that it works on non-clients is probably just an oversight... if it was intended to work on non-clients it woulda been an entity index, not a client state index.

Paril, did you read the comment in R1ch's code that I specifically cited for a reason?

"// server is able to read clientNum field from gclient_s struct and hide appropriate entity from client"

It does not say anything about the specified entity needing to be another client. Thank you for sharing your purely conjectured opinion of what R1ch intended.

**Comment by Paril** [comment]
This isn't the place to be argumentative - my point was to lay out the challenges in changing this assumption. The GMF_CLIENTNUM feature was essentially a port from the equivalent Quake III Arena feature; it's also called `clientNum` and ranges from 0 to MAX_CLIENTS - 1. It's meant to point to a client state index, which is why it's not an entity index. It just *happens* to work on entities in q2pro because it was never bounds checked, and it'd be a confusing contract if you had to keep it offset by 1 for a particular entity (ie to hide entity 270 you'd set clientNum to 269).

It's certainly possible to make this work the same way as it does in r1q2 for hiding a single entity but care will have to be taken to not break the existing assumptions in q2pro that clientNum is always.. well, a client number.

**Comment by skullernet** [comment]
Paril is right, clientNum was from its inception intended to be a way for game lib to indicate current POV entity number to client. It is explicitly communicated to client in Q2PRO protocol 36, so that the Q2PRO client can take appropriate action (hide entity from renderer, make sound from this entity full volume, etc). This cannot be changed without breaking Q2PRO protocol.

Indeed, when client is using protocol 34 or 35 the server merely resets modelindex on such entity as a workaround. But this is purely coincidental and definitely should not be relied upon to hide arbitrary entities from clients. Comment in R1Q2 code only describes R1Q2 server implementation detail, not how clientNum is supposed to be used.

**Comment by ThePhatman** [comment]
> clientNum was from its inception intended to be **a way for game lib to indicate current POV entity number to client. **

Which if viewing the POV of a monster is indeed the POV of an entity number.

> It is explicitly communicated to client in Q2PRO protocol 36, so that the Q2PRO client can take appropriate action (hide entity from renderer, make sound from this entity full volume, etc). This cannot be changed without breaking Q2PRO protocol.

Because it was encoded as a byte. That's a shame.

> Indeed, when client is using protocol 34 or 35 the server merely resets modelindex on such entity as a workaround. But this is purely coincidental and definitely should not be relied upon to hide arbitrary entities from clients. 

It is being used to view the POV of a monster, not as a substitute for SVF_NOCLIENT, which I have used extensively.

> But this is just a side effect and definitely should not be relied upon to hide arbitrary entities from clients.

I believe you have inferred incorrectly what I was attempting to do with it.

> Comment in R1Q2 code only describes R1Q2 server implementation detail, not how clientNum is supposed to be used.

It is supposed to be used to hide the model of entity to show its POV, which is what I am doing. Except that the POV is (unexpectedly) a monster's and not another player's.  It is clear to me that you both seem to have inferred that I was trying to misuse it to do what essentially what SVF_NOCLIENT does or something to that effect...

Paril:

> It seems like R1Q2 only used clientNum to hide an entity, and nothing more

skullernet:

> clientNum was from its inception intended to be a way for game lib to indicate current POV entity number to client

Your argument regarding its intended use from inception is somewhat poor, given its inception is from Quake 3 which has no monsters and that [monster POVs could conceivably be ones a Quake 2 game library author would want to (at least temporarily) see the world through](https://www.youtube.com/watch?v=OUO4Jie51co).

Is there any way for the game library to prevent protocol 36 from being used?

**Comment by skullernet** [comment]
Yes, it appears there was as confusion as you didn't state clearly that you are trying to view game from the POV of the monster, and instead talked about hiding entities which is not GMF_CLIENTNUM primary purpose, but a side effect.

Indeed, I've never thought about the need of setting client POV to something other than other client, thus clientNum is transmitted through network as a byte and things will break if it overflows. I suppose protocol 36 can be extended to transmit clientNum as a short, but this will only work with updated clients, obviously.

There is no way to prevent protocol 36 from being used server-side.

**Comment by ThePhatman** [comment]
> Yes, it appears there was as confusion as you didn't state clearly that you are trying to view game from the POV of the monster, and instead talked about hiding entities which is not GMF_CLIENTNUM primary purpose, but a side effect.
> 
> Indeed, I've never thought about the need of setting client POV to something other than other client, thus clientNum is transmitted through network as a byte and things will break if it overflows. I suppose protocol 36 can be extended to transmit clientNum as a short, but this will only work with updated clients, obviously.
> 
> There is no way to prevent protocol 36 from being used server-side.

I do not believe you or I introduced the confusion, though I admit that I did not declare exactly what I was using it for.  Thank you for considering a future revision of the protocol, I leave that decision in your capable hands.

Given the information you've kindly provided me regarding how protocol 36 works with clientNum and the fact that I don't anticipate really needing the in-eyes mode for enemy Strogg (only allied), the workaround solution seems patently obvious to me.

I will leave the decision to close this issue as you see fit, I am satisfied with the results of our conversation and thank you for the information.

**Comment by ThePhatman** [comment]
Thank you!

**Comment by ThePhatman** [comment]
> Yes, it appears there was as confusion as you didn't state clearly that you are trying to view game from the POV of the monster, and instead talked about hiding entities which is not GMF_CLIENTNUM primary purpose, but a side effect.
> 
> Indeed, I've never thought about the need of setting client POV to something other than other client, thus clientNum is transmitted through network as a byte and things will break if it overflows. I suppose protocol 36 can be extended to transmit clientNum as a short, but this will only work with updated clients, obviously.
> 
> There is no way to prevent protocol 36 from being used server-side.

I've figured out a workaround which allows me to disable protocol 36 for a client when an older version of q2pro is detected. From within the game library, I poll the client and server's version strings and if they are both using q2pro I check if either revision is less than "2161". If so, I stuff a "cl_protocol 34" to the client and direct it to connect to $cl_server (stuffing a reconnect does not seem to effectively change the protocol when it does reconnect).

Would you like me to file that issue with reconnect not checking cl_protocol as an issue or do you wish to retain the current behavior?

**Comment by ThePhatman** [comment]
> There is no way to prevent protocol 36 from being used server-side.

My game library will now successfully force a client to use protocol 34 if either the server or client is using a q2pro revision earlier than 2161. However I noticed that if a client is connected then sets cl_protocol to 34 and uses the reconnect command, it still uses protocol 36 after reconnecting. So I ended up using `connect $cl_server` from the client instead, which will respect the cl_protocol setting.

Would you like me to file that as a new issue or is the current behavior preferred for general use-cases? If you do not respond to this comment within a week, I will file it as a new issue to ensure you are aware of it in case you don't read this comment given that this current issue is closed.

**Comment by skullernet** [comment]
> I noticed that if a client is connected then sets cl_protocol to 34 and uses the reconnect command, it still uses protocol 36 after reconnecting.

`cl_protocol` is only respected on initial connect, I think. So reconnect will use original value of the protocol. Honestly I don't see a big issue here.

> My game library will now successfully force a q2pro client to use protocol 34 if the server is running q2pro and either the server or client is using a revision earlier than 2161.

You shouldn't downgrade pre-r2161 clients to protocol 34 or 35 because r2161 or higher server will automatically apply clientNum workaround for them. If server is running older version then you are indeed out of luck. But at least force protocol 35, because 34 is very inefficient. Or maybe print a big warning and tell the server admin to upgrade to latest version.

**Comment by ThePhatman** [comment]
> `cl_protocol` is only respected on initial connect, I think. So reconnect will use original value of the protocol. Honestly I don't see a big issue here.

Sounds good. That's why I asked if it was the preferred behavior for general use-cases, which I have no formed opinion about.

> You shouldn't downgrade pre-r2161 clients to protocol 34 or 35 because r2161 or higher server will automatically apply clientNum workaround for them. If server is running older version then you are indeed out of luck. But at least force protocol 35, because 34 is very inefficient. Or maybe print a big warning and tell the server admin to upgrade to latest version.

Good to know regarding newer servers being able to do a workaround for pre-r2161 clients, I will accordingly remove that branch of conditions, under which it steps down the protocol.

During my testing with Q2Pro (server r2164 and an older client version), I found that protocol 35 will cause the client to freeze up for a few seconds while in the Strogg in-eyes chase mode when there are a lot of other entities around. This does not seem to occur when using protocol 34 with the same client-server combination.

**Comment by skullernet** [comment]
> I found that protocol 35 will cause the client to freeze up for a few seconds while in the Strogg in-eyes chase mode when there are a lot of other entities around. This does not seem to occur when using protocol 34 with the same client-server combination.

That's odd. If protocol 35 freezes then 34 should freeze too. They only way I can imagine this happening is if `net_maxmsglen` is set too low on the client.

**Comment by darkshade9** [comment]
We've noticed this behavior in protocol 38 changes connecting to protocol 35 servers (tastyspleen for example), where the player camera from the player model gets 'detatched'.

**Comment by ThePhatman** [comment]
> That's odd. If protocol 35 freezes then 34 should freeze too. They only way I can imagine this happening is if `net_maxmsglen` is set too low on the client.

I have returned to using protocol 35 with q2pro clients on older q2pro server versions and will report back to you if this issue re-occurs. As stated before, I use SVF_NOCLIENT extensively (to reduce the number of active entities being signaled to clients) and my entity priority table has since changed in order to improve general performance. However my changes are game library side only and I do not see how they (solely) would have caused the client to freeze up on a rendered frame. Barring reproducing the issue, nor can I conclude that it was (strictly) protocol 35 related either.

So please disregard that report for now and I will let you know if it reoccurs when I ramp up to a full-time play-test server. I will run an older version of q2pro as the server during (some of ) the testing to try to reproduce the issue.
