### ISSUE TITLE
Gun models look messed up like they are camoflaged

### ISSUE THREAD

**Issue by ghost** [skullernet/q2pro#263]
https://imgur.com/LO6NQLC.png

Linux Mint 21

![image](https://user-images.githubusercontent.com/94876428/187681633-6492e4d2-dac4-411f-b221-def8a8075e1e.png)

**Comment by skullernet** [comment]
Looks like you have some custom texture pack installed (possibly also custom model pack, hard to tell from screenshot), and the skin doesn't match the model. Try with `r_override_textures 0`.

**Comment by Paril** [comment]
You've probably got Q2RTX installed over top of this. Rename the q2rtx_media.pkz pack to work around it.
