### ISSUE TITLE
TRANS33|TRANS66 alphatest texturing

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#265]
A fairly common early extension in the Q2 world was to use this mutually exclusive combination of flags to indicate alpha-test textures (for foliage, etc), q2pro doesn't seem to support it though.

**Comment by skullernet** [comment]
How common is it? I don't know any Q2 engine that interprets these flags this way. Q2PRO supports SURF_ALPHATEST for alpha test surfaces (this flag was imported from KMQuake2).

**Comment by Paril** [comment]
That's a good question actually - KMQuake2 was supposed to support the former, but he went with a new flag for some reason even though it should be perfectly acceptable to just pass the former through the latter. We use that flag combo in Q2RTX and some other stuff I've been working on, and the actual usage of the flag mixture dates back to quite a long time ago, I remember seeing it in some random tutorial page, but it may be lost to time now.

Digital Paintball 2 also uses it, but it's not really a Q2 engine so it doesn't really count. KMQ2's flag is already in the wild so it's probably something we'd have to support regardless, but I like the 33|66 mixture because it degrades better for older engines (will be semi-transparent rather than opaque).

**Comment by skullernet** [comment]
I don't think it's safe to assume (TRANS33|TRANS66) flags are meant to signify alpha tested surface. I run a check on a [corpus](http://tastyspleen.net/quake/downloads/all-maps.zip) of maps and there are [plenty](https://gist.github.com/skullernet/ec16035413926be1fcf78069a11f04dd) of maps that have surfaces with both flags set. While there are some maps that use both of these flags on surfaces meant to be alpha tested, there are also cases where these flags are used on ordinary transparent surfaces drawn with opaque texture and alpha value of 0.33. If suddently we start to interpret (TRANS33|TRANS66) as alpha-tested then these surfaces will no longer be transparent.

**Comment by Paril** [comment]
Interesting! Thanks for the research. Knightmare says that the 33|66 thing came from Quake2Max, and initially meant that it had 99% opacity (254 alpha), that must be what I had read all those years ago.

I think we'll just stick to the kmq2 flag in that case.
