### ISSUE TITLE
Probable bug with client download command

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#270]
I noticed when doing some testing with the client `download` command that it was not respecting the "allow downloading" setting in the menu (options -> download options -> allow downloading).

The `-1` on [this line of code](https://github.com/skullernet/q2pro/blob/master/src/client/download.c#L923) seems to be the issue. When "allow downloading" is set to "no" the `allow_download` variable value is actually `0`.

This feature is important to some of the work I'm doing on `The Strogg Pharm Coop` server, but I would like to respect the user's choice regarding downloading **extra** media (PCX files in this case). Therefore I will be checking the client's setting before issuing the command to the client to prevent undesired downloads.

Thank you.

**Comment by skullernet** [comment]
`download` command is for manual downloads/debugging. If you are stuffing it to the client from server you are doing it wrong. To make client download stuff according to its settings, you need to precache extra media via `gi.configstring()`, or enable HTTP downloads and set up a filelist.

"allow downloading" settings from menu and `allow_download*` cvars control automatic downloads only. The only exception is special value -1 for `allow_download` which locks out all kinds of downloads, including `download` command to prevent abusive servers from stuffing it. This is an advanced feature and therefore not supported in menu.

**Comment by ThePhatman** [comment]
No, I do indeed [know how to pre-cache media](https://github.com/nowantny/q2dos-the-pot/blob/main/coop/g_spawn.c#L1502).

This semantic seems to be unique to Q2Pro as I [do not see it in the R1Q2](https://github.com/tastyspleen/r1q2-archive/blob/dfe96b760572afb74fcdfdf773b0e6ca96e1d813/client/cl_main.c) nor [the original Quake II](https://github.com/id-Software/Quake-2/blob/master/client/cl_main.c#L1126) source code versions.

Given the explanation of your non-standard (boolean) use of the cvar, I will have the client report their `allow_download` setting to the game and if they are running Q2Pro I will prevent the game library from pushing the content if the value is `-1`.

**Comment by skullernet** [comment]
Ah, I've meant `gi.*index()` functions, not `gi.configstring()` for precaching. But I'm not sure why you insist on using `download`. Precaching will ensure all downloads are complete before client enters the level. Stuffing `download` mid-game will freeze the client for duration of download (unless using HTTP).

**Comment by ThePhatman** [comment]
During my testing with the original Quake II client, I did not find that it froze during UDP downloads (though I'm using a fast connection where it would conceivably bottleneck a dial-up connection, should anyone still be using them). So I went to check out what you were saying about UDP downloads freezing the client during the download with Q2Pro by disabling HTTP downloads in the client and it still used HTTP none the less. So then I restarted the client and verified that the setting was still set to `HTTP downloads -> no` and it was, so I tried it again -- same thing. I think you may have an issue there given that the `download` command will use HTTP (if compiled into the client) regardless of the setting. It seems to be in how `CL_Download_f()` calls `check_file_len()` where `cl_http_downloads` does not seem to be checked along the call path. However I won't open a new issue for the `download` command ignoring the HTTP downloads setting, unless you would like me to.

Furthermore, in other testing I found that with the original Quake II client if a picture was missing at the client and the game state attempted to display it, it displayed a message `Can't find pic:` repeatedly in the console until the UDP transfer completed and then it would immediately successfully display the image. Likewise R1Q2 would display a red checkered pattern in the top-left corner of the picture's (x, y) location until the download had completed and then would successfully display the image as soon as the transfer completed. Whereas Q2Pro seems to cache the result of the file system check and even after the download has completed, it will not check the file system again.

Given the results of my research into the various Quake II clients, I have decided how I will be dealing with my use case such that I will not be stuffing the `download` command to Q2Pro clients at all. Precaching 100+ PCX files in case they might get used is not really an option when some clients do not have the use of HTTP transfers available and there exists the possibility that I might have up to 700 PCX files if I go with a richer design. In the case of Q2Pro clients, it will be the filelist mechanism before they enter the game or nothing whereas some other clients will get the media transferred as needed.

If you want more details regarding my use case, please contact me at asa dot cherub at gmail dot com.

Cheers and thank you for your contribution to the Quake II legacy community.

**Comment by skullernet** [comment]
> During my testing with the original Quake II client, I did not find that it froze during UDP downloads.

Now as I recall it original Quake 2 server will indeed multiplex download with normal frame activity. Q2PRO server, however, will stop sending client frames for duration of download to maximize throughout. Initially, I thought R1Q2 server will also do this but looking at the code it seems like it won't. Not sure where I got this idea from.

> I think you may have an issue there given that the download command will use HTTP (if compiled into the client) regardless of the setting.

Can't reproduce this. However, one needs to reconnect to the server for `cl_http_downloads` change to take effect. The only place where `cl_http_downloads` is checked is [here](https://github.com/skullernet/q2pro/blob/master/src/client/http.c#L525) in `HTTP_SetServer()`. If it is set to 0 then no HTTP server is set and HTTP downloads can't work in principle.

>  It seems to be in how CL_Download_f() calls check_file_len() where cl_http_downloads does not seem to be checked along the call path.

This is normal because Q2PRO uses download queue for UDP downloads as well, not just HTTP.

> Whereas Q2Pro seems to cache the result of the file system check and even after the "manual" download has completed, it will not check the file system again.

Yes, Q2PRO basically requires all media to be precached/downloaded before clients enters the game, as there are multiple levels of caches. You can issue `r_reload` command to flush the cache after manual downloading. But users will probably hate you for his :)

> there exists the possibility that I might have up to 700 PCX files if I go with a richer design

700 PCX files is indeed not something you can precache at once. Pre-distributing them, or using HTTP filelist seem to be the only option.

**Comment by ThePhatman** [comment]
> Not sure where I got this idea from.

I'll take it upon myself to presume you were being thoughtful of anyone with low bandwidth.

> Can't reproduce this.

I just reproduced it again.

1. q2pro r2230 client on Windows 64-bit
2. Server is offering an HTTP server to download from
3. Allow downloading is yes
4. HTTP downloads is no
5. The client was started with those settings in place (shut down the process and started it again)
6. Confirmed after connecting to the server again that `cl_http_downloads` was 0
7. Used the download command to download a WAV sound from the sound/misc directory on the server

> The only place where cl_http_downloads is checked is [here](https://github.com/skullernet/q2pro/blob/master/src/client/http.c#L525) in HTTP_SetServer(). If it is set to 0 then no HTTP server is set and HTTP downloads can't work in principle.

`CL_Download_f()` [never calls](https://github.com/skullernet/q2pro/blob/master/src/client/download.c#L935) `HTTP_SetServer()`. 

> You can issue r_reload command to flush the cache after manual downloading. But users will probably hate you for his :)

That may come in handy. I just tried it on my system and it resumed the game in under a second. But then I do keep my Q2Pro client on a RAM drive which *might* influence the results in this case. 

Thanks for the information and please let me know if you need further information about the environment where I reproduced the above use of HTTP download despite `cl_http_downloads` setting issue (again).
