### ISSUE TITLE
request: url encoding http downloads

### ISSUE THREAD

**Issue by MVarland** [skullernet/q2pro#275]
http downloads won't work for filenames containing special characters. e.g. textures/coventry/+1centrum.wal

Q2pro would need to be built with url encoding enabled, to convert + into %2B (example:  https://aqtion.downloadserver.site/textures/coventry/%2B1centrum.wal) and ensures that the file downloaded de-encodes the filename back to +1centrum.wal

**Comment by skullernet** [comment]
Q2PRO already does URL encoding. It uses non-standard code inherited from R1Q2 to do so however, which explicitly doesn't escape characters defined as reserved by RFC 3986. Not sure what rationale that code has, make the client behave more like web browser perhaps? But indeed, this approach seems to have problems, at least with lighttpd, which interprets `?` character in a special way. Guess reserved characters need to be escaped, after all.
