### ISSUE TITLE
Can't open menu on Linux

### ISSUE THREAD

**Issue by rykerOnGithubDotCom** [skullernet/q2pro#276]
I built q2pro from a make file on Linux and pressing escape or typing in togglemenu in console does absolutely nothing.

**Comment by skullernet** [comment]
As there is no install target in regular Makefile, you need to manually copy `src/client/ui/q2pro.menu` to `baseq2/`.

**Comment by tojestzart** [comment]
> I built q2pro from a make file on Linux and pressing escape or typing in togglemenu in console does absolutely nothing.

skuller has recently swapped from compilation method to new one, propably forgot about few things, i had a ticket related to it before, and yes its q2pro.menu

**Comment by 12sunflowers** [comment]
> I built q2pro from a make file on Linux and pressing escape or typing in togglemenu in console does absolutely nothing.

same here on Linux
