### ISSUE TITLE
allow movement keys while menu is opened

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#283]
Right now movement keys are just stuck while menu is opened. Since we dont have some sort virtual menu system, your menu is close but  make it a bit more useful with this little thing :)
Using a menu to click on radio messages while moving would be quite nice QOL ;)

**Comment by skullernet** [comment]
> Right now movement keys are just stuck while menu is opened.

This is not true, `-button` commands are still executed while menu is open, which means no buttons should be stuck.

> allow movement keys while menu is opened

This can't work with current menu system. Menu hardcodes a lot of keys (including default movement keys), and doesn't care if these keys are bound to a command. The only solution is to disallow `+button` commands while menu is open.
