### ISSUE TITLE
Can't fetch 'http://q2servers.com/?raw=2', no HTTP support compiled in

### ISSUE THREAD

**Issue by 12sunflowers** [skullernet/q2pro#284]
Hello. Build on Slackware 15 using just
`make -j'nproc'`
game build successfully 
game run good
but i cant connect to server list
`Can't fetch 'http://q2servers.com/?raw=2', no HTTP support compiled in.`
What wrong? Its compilation issue?

**Comment by 12sunflowers** [comment]
SOLVED
Need copy .config file from /doc/examples/buildconfig
and edit enabling HTTP downloads
```
# Enable HTTP downloads by linking against libcurl.
CONFIG_HTTP=y
```
and make build again

**Comment by skullernet** [comment]
Building using Makefile is deprecated. You need to build with Meson which will autodetect installed dependencies.

**Comment by 12sunflowers** [comment]
Here on Slackware Meson is too older that needed.
I am just create .config and do `make` I am do not install any decencies and do not configure.
