### ISSUE TITLE
Feature: Physically based rendering

### ISSUE THREAD

**Issue by ndit-dev** [skullernet/q2pro#286]
I have no insight in how complicated it would be to implement. But it would be really nice to be able to use stylized textures within q2pro

**Comment by skullernet** [comment]
> Physically based rendering

I have no idea what this is, but if it is something similar to what is described in this [article](https://en.wikipedia.org/wiki/Physically_based_rendering) than I have to say it is out of scope of Q2PRO project. In general, any rendering enhancements that change original Quake 2 look and feel are not planned. There are many other source ports that work on that kind of thing.

**Comment by ndit-dev** [comment]
Yes exactly, by adding additional texture-maps you can depending on the implementation affect the roughness of the surface, how light bounces of it, etc.
[example project with opengl](https://github.com/Nadrin/PBR)

fully understand that this is outside of this project, thought it would be a cool way to bring new life to old maps and models.

**Comment by neveride84** [comment]
I agree with @skullernet. It should not be implemented in q2pro. You could think about doing it in its port. Check Q2 RTX: https://github.com/NVIDIA/Q2RTX

**Comment by ndit-dev** [comment]
> I agree with @skullernet. It should not be implemented in q2pro. You could think about doing it in its port. Check Q2 RTX: https://github.com/NVIDIA/Q2RTX

Thanks for pointing me there, Q2RTX seem to have implemented it already and documented the use here https://github.com/NVIDIA/Q2RTX#material-system for anyone else interested in playing with it.
