### ISSUE TITLE
diffrent crosshair per weapon using command 'if'

### ISSUE THREAD

**Issue by KOKOSv8** [skullernet/q2pro#288]
Is there anyway to setup diffrent crosshair for each weapon other than bind, so it can be automatically?
There is client macro cl_weaponmodel, that maybe could be used with command IF ?
How exactly IF works? In console it says "Usage: if < expr > < op > < expr > [then] < command > [else < command >]"
What means op in if command?

**Comment by skullernet** [comment]
> Is there anyway to setup diffrent crosshair for each weapon other than bind, so it can be automatically?

No, I don't think so.

> There is client macro cl_weaponmodel, that maybe could be used with command IF ?

It can be used with `if`, but it still needs to be externally triggered with a bind.

> What means op in if command?

Comparison operator, list of valid operators is [here](https://github.com/skullernet/q2pro/blob/master/src/common/cmd.c#L640).

**Comment by neveride84** [comment]
You could go down this route:
```
set cl_gun "-1"

alias +attck "+attack"
alias -attck "-attack;weap_${cl_weaponmodel};noammo_check_${cl_blaster}"
bind mouse1 "+attck"

alias weap_models/weapons/v_blast/tris.md2 "set crosshair 1"
alias weap_models/weapons/v_machn/tris.md2 "set crosshair 1"
alias weap_models/weapons/v_shotg/tris.md2 "set crosshair 1"
alias weap_models/weapons/v_rocket/tris.md2 "set weapon RL; set crosshair 3"
alias weap_models/weapons/v_shotg2/tris.md2 "set weapon SSG; set crosshair 1"
alias weap_models/weapons/v_launch/tris.md2 "set weapon GL; set crosshair 1"
alias weap_models/weapons/v_handgr/tris.md2 "set crosshair 1"
alias weap_models/weapons/v_hyperb/tris.md2 "set weapon HB; set crosshair 1"
alias weap_models/weapons/v_chain/tris.md2 "set weapon CG; set crosshair 1"
alias weap_models/weapons/v_rail/tris.md2 "set weapon RG; set crosshair 2"
alias weap_models/weapons/v_bfg/tris.md2 "set weapon BFG; set crosshair 1"

```

**Comment by KOKOSv8** [comment]
Thanks neveride84 for idea, I manage to make it pretty much automatically sticking into movement keys.

set modifier 0

bind "d" "+d(${modifier})"
alias "-d(0)" "-back; ${cl_weaponmodel}"
alias "-d(1)" "-back"
alias "+d(0)" "+back; ${cl_weaponmodel}"
alias "+d(1)" "+back"
bind "e" "+e(${modifier})"
alias "-e(0)" "-forward; ${cl_weaponmodel}"
alias "-e(1)" "-forward"
alias "+e(0)" "+forward; ${cl_weaponmodel}"
alias "+e(1)" "+forward"
bind "f" "+f(${modifier})"
alias "-f(0)" "-moveright; ${cl_weaponmodel}"
alias "-f(1)" "-moveright"
alias "+f(0)" "+moveright; ${cl_weaponmodel}"
alias "+f(1)" "+moveright"
bind "s" "+s(${modifier})"
alias "-s(0)" "-moveleft; ${cl_weaponmodel}"
alias "-s(1)" "-moveleft"
alias "+s(0)" "+moveleft; ${cl_weaponmodel}"
alias "+s(1)" "+moveleft"

alias models/weapons/v_blast/tris.md2 "set crosshair 28; set ch_scale 0.3"
alias models/weapons/v_machn/tris.md2 "set crosshair 5; set ch_scale 0.4"
alias models/weapons/v_shotg/tris.md2 "set crosshair 6; set ch_scale 0.5"
alias models/weapons/v_rocket/tris.md2 "set crosshair 4; set ch_scale 0.3"
alias models/weapons/v_shotg2/tris.md2 "set crosshair 14; set ch_scale 0.5"
alias models/weapons/v_launch/tris.md2 "set crosshair 4; set ch_scale 0.3"
alias models/weapons/v_handgr/tris.md2 "set crosshair 16; set ch_scale 0.3"
alias models/weapons/v_hyperb/tris.md2 "set crosshair 7; set ch_scale 0.4"
alias models/weapons/v_chain/tris.md2 "set crosshair 9; set ch_scale 0.4"
alias models/weapons/v_rail/tris.md2 "set crosshair 28; set ch_scale 0.3"
alias models/weapons/v_bfg/tris.md2 "set crosshair 12; set ch_scale 0.4"
