### ISSUE TITLE
gl_dynamic options

### ISSUE THREAD

**Issue by KOKOSv8** [skullernet/q2pro#289]
1. Could you add option please to change color of particle light which is yellow currently? In yamagi there is option cl_r1q2_lightstyle "1" that makes them red and it fits better as its toned down and doesnt feel that "flashy".
![q2_0001](https://user-images.githubusercontent.com/123253141/218342026-2f97b1fc-465a-4f64-b411-71c8420d467c.jpg)

2. Could you add option please to change how big explosion is? It feels way too big, I have tested yamagi last time and there seems to be smaller radius which is better for multiplayer.
YAMAGI EXPLOSION
![q2_0005](https://user-images.githubusercontent.com/123253141/218342158-7853ac8b-3847-4e5e-9e4e-9940e508778a.jpg)
Q2PRO EXPLOSION
![quake072](https://user-images.githubusercontent.com/123253141/218342179-1fd4eb53-a817-47b8-9bb5-a8dad45ab8c8.jpg)

3. Any chance to have command to turn off gl_dynamic on certain weapon so I can still get it on other weapons, please? Mostly its about machinegun and chaingun that makes screen super flashy and make eyes tired faster but maybe color change would fix it.

**Comment by skullernet** [comment]
Added `cl_dlight_hacks` to address these. E.g. to make rocket light red, explosions smaller, and disable muzzle flashes for MG/CG, set it to `7`.

**Comment by KOKOSv8** [comment]
Wow, thats awesome ! now this client is super close to perfection, big thanks
