### ISSUE TITLE
Implementing GetExtendedGameAPI()

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#294]
Hello!

Regarding this commit https://github.com/skullernet/q2pro/commit/73ab2a2a7b23e793c519c07c0532ab16ce268052

I'm interested in implementing the features that GetExtendedGameAPI() provides into Action Quake, is there a quick rundown on the best way to accomplish this?  I'm very much a C novice, and I read in the comments of the commit that I should not be copying the structure, and that it behaves differently than GetGameAPI().  I didn't see any implementation details in `baseq2` to use an an example, I assume it doesn't need it?  Any insights or guidance would be greatly appreciated.

**Comment by skullernet** [comment]
It behaves largely the same as GetGameAPI(), with additional provision that import/export structures may be extended in the future. To accomplish this, both import/export structures are versioned. They also must not be copied because structure sizes may differ between server and game library.

No game mods use this feature yet, so there are no real world examples.

Quick useless example that will print contents of `test.txt` file on `fs_restart`:

```
static const game_import_ex_t *gix;

static void RestartFilesystem(void)
{
    char *buffer;

    // load file (possibly from packfile)
    gix->LoadFile("test.txt", (void **)&buffer, 0, TAG_GAME);
    if (buffer) {
        // do something with it
        gi.dprintf("%s", buffer);

        // free memory
        gi.TagFree(buffer);
    }
}

static const game_export_ex_t gex = {
    .apiversion = GAME_API_VERSION_EX,
    .RestartFilesystem = RestartFilesystem,
};

q_exported const game_export_ex_t *GetExtendedGameAPI(const game_import_ex_t *import)
{
    gix = import;   // assign pointer, don't copy!
    return &gex;
}
```

**Comment by skullernet** [comment]
You are doing something very odd. There is no need to add prototypes for `FS_ListFiles`, etc, in game code. Also, your `game_export_ex_t` structure definition is wrong. Why is it identical to `game_import_ex_t`? You need to copy structure definitions from Q2PRO header file verbatim.

**Comment by darkshade9** [comment]
Given my experience level and limited knowledge of how the original GameAPI interacts with the game library, I fell mostly into it via trial and error.  I'm not sure how or if I accidentally got some result out eventually getting it to output something meaningful.  I removed the prototypes in `g_local.h`, though if I modify `game_export_ex_t` or `game_import_ex_t` at all (if I copy verbatim from Q2Pro), I run into all kinds of issues.
