### ISSUE TITLE
it looks like all of the 2023 versions wont load autoexec.cfg

### ISSUE THREAD

**Issue by Unh0lyq2** [skullernet/q2pro#295]
### Before reporting bugs

Make sure the bug is reproducible with latest Q2PRO version. If you compile
Q2PRO yourself, update to the latest version from git master. If you are using
prebuilt Windows binaries, update to the latest version available from
https://skuller.net/q2pro/nightly/

### Important information

Provide the following information:
- Q2PRO version
- OS version
- GPU driver and version

For Linux:
- Linux distribution and version
- Window manager version

### Reproduction steps

Steps to reproduce the behavior.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

If reporting graphics glitches, provide screenshot or video.

### Log file

Provide a link to the log file created by launching `q2pro +set developer 1
+set logfile 1`.

### Crash reports

If Q2PRO crashes, provide a crash report (Windows) or a backtrace (Linux). On
Linux, backtrace can be created by launching Q2PRO with `gdb q2pro --args
[...]` and typing `bt` after the crash.

**Comment by amokmen** [comment]
Works for me (Ubuntu 18, Q2PRO builded at 2023-02-08 with options "system-wide": false):

```sh
# create file 'autoexec.cfg'
touch baseq2/autoexec.cfg

# run q2pro binary
./q2pro

...
Execing config.cfg
Execing autoexec.cfg
...
```

^^ "Execing autoexec.cfg" means that engine successfully found and executed file "autoexec.cfg" inside "baseq2" directory.

Check search paths for your q2pro by running it and typing in console command `path`:

```
]path
Current search path:
./baseq2/pak2.pkz (203 files)
./baseq2/pak1.pkz (271 files)
./baseq2/pak0.pkz (1095 files)
./baseq2
```

**Comment by skullernet** [comment]
This doesn't look like a valid bug report.
