### ISSUE TITLE
newer builds have problems with translucent models alpha channel

### ISSUE THREAD

**Issue by voivodpl** [skullernet/q2pro#302]
```

				gi.setmodel(bloodsp, "models/objects/bpool/tris.md2");
				bloodsp->s.renderfx |= RF_NOSHADOW;
				bloodsp->s.renderfx |= RF_TRANSLUCENT;
```
![quake007](https://github.com/skullernet/q2pro/assets/45218752/7e0039ce-1db7-4c89-9b8d-acdaa67be9f0)
Newer builds have problems with translucent models alpha channel, the alpha channel is not fully transparent and leaves a black square semi-transparent black space.
Same results on both Nvidia and AMD GPUs, replacing with q2pro r1836 fixes the problem (didn't try other versions, only the newest and this).

**Comment by voivodpl** [comment]
Sorry, I think I loaded 32 bit version of the game dll. Investigating further.

**Comment by voivodpl** [comment]
Yeah, no matter if 32 bit or 64 bit client. The newer(st) ones draw models with translucent textures like this.

**Comment by QwazyWabbitWOS** [comment]
Confirmed to be an issue in q2pro64_r2654 and q2pro64_r2681 and not an issue in q2rtx_v160 in OpenGL mode and not an issue in older q2pro_r1861. The transparent areas would seem to be semi-transparent. Could this be due to a minimum default alpha transparency in the renderer?


![quake002](https://github.com/skullernet/q2pro/assets/22873115/abf7d5ff-15aa-4568-9b17-a1b36921ccdd)
![quake003](https://github.com/skullernet/q2pro/assets/22873115/612aca81-a769-43e3-9717-abbb70bde4ee)

**Comment by skullernet** [comment]
These seem like shadows to me. Does disabling shadows (`gl_shadows 0`) make them disappear?

**Comment by QwazyWabbitWOS** [comment]
Yes, setting gl_shadows 0 makes them disappear. How can one make the model not cast a shadow?

**Comment by skullernet** [comment]
Then ffc80035ede is the cause of this. You need to update RF_NOSHADOW definition in your mod. Previously, it was an engine private constant, and not part of network protocol. In newer versions it has been moved to public header and redefined to a different value (8192) some other engines also use (e.g. YQ2).

**Comment by voivodpl** [comment]
> Then [ffc8003](https://github.com/skullernet/q2pro/commit/ffc80035ede785d2987120ae1b236ff0cb88eec3) is the cause of this. You need to update RF_NOSHADOW definition in your mod. Previously, it was an engine private constant, and not part of network protocol. In newer versions it has been moved to public header and redefined to a different value (8192) some other engines also use (e.g. YQ2).

Fixed. Thanks!
