### ISSUE TITLE
Microsoft Defender threat - win32/defenseevasion.a!ml

### ISSUE THREAD

**Issue by djaycse** [skullernet/q2pro#307]
Hi there. My q2pro.exe has been flagged a couple of times in recent weeks by Microsoft Defender as a threat: `win32/defenseevasion.a!ml`. Guessing it's a false positive?

Versions I was using: 2697.0.0.0 and 2702.0.0.0

The exes were working fine for weeks, then suddenly while I was in game jumping around, the game stopped (felt like it crashed) and I was back on my desktop. Tried running the game again and q2pro.exe was missing. Checked Defender and it showed this:
![q2pro](https://github.com/skullernet/q2pro/assets/95850520/0aa0bae5-e02e-44c3-aa79-6ef03038a117)

I've upgraded to your latest build 2710.0.0. Will monitor and see how it goes.

I actually don't think it's the exe, but maybe some new Microsoft Defender definitions that's being extra vigilant/strict.  I could temporarily exclude the file from future checks, but wanted to notify you in case it's something worth investigating.

Anyway hope this helps on your end. Thanks for all your efforts over the years by the way!

**Comment by skullernet** [comment]
Most likely a false positive. Nothing I can do about it.

**Comment by djaycse** [comment]
All good. I've added q2pro.exe to the exclusion/allow list. Thanks.
