### ISSUE TITLE
regression on r2765 black white 

### ISSUE THREAD

**Issue by tojestzart** [skullernet/q2pro#308]
### Before reporting bugs

https://skuller.net/q2pro/nightly/

### Important information
r2765 - winx64
APU vega 8 30.0.13002.23 
RTXm 3050 27.21.14.6275
(not sure which one it wants to run , but propably AMD)

### Reproduction steps

Run exe and dont work

### Expected behavior

Menu screen with choice

### Actual behavior

Black white

### Screenshots

https://www.youtube.com/shorts/tlr4o1FsZSY

### Log file

[console.log](https://github.com/skullernet/q2pro/files/12417535/console.log)

### Crash reports

N/A for now since i dont have set debugging environment (not for me)

ps. downloaded your archived random build from high number (r2617) and it works.

**Comment by skullernet** [comment]
Please test the latest nightly build.

**Comment by tojestzart** [comment]
still not :(
[console.log](https://github.com/skullernet/q2pro/files/12418771/console.log)
i  have a feeling it takes much longer to load that executable for some reason also, had to remove old log file to create fresh one (i thought it will be replaced itself)

**Comment by tojestzart** [comment]
i just realized.... it was downloading for some reason old compilation? chrome extensions?? or something?
works now, thanks!
[console.log](https://github.com/skullernet/q2pro/files/12420323/console.log)

**Comment by tojestzart** [comment]
close with comment
