### ISSUE TITLE
bug with homedir/basedir on Windows, EACCES

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#316]
When using a full absolute path for homedir or basedir, `FS_CreatePath` will fail with EACCES, as it attempts to mkdir the root drive and counts that as a failure. This causes config files, screenshots, etc to never be allowed to be written.

Can be reproduced with the following call: `FS_CreatePath("C:/test/")` - even though the directory is writable and valid, it will fail before it even gets to `/test/` as mkdir on `c:/` fails early.

**Comment by Paril** [comment]
A quick fix I've made for now:

```
#ifdef _WIN32
    // check for UNC path and skip "//computer/share/" part
    if (*path == '/' && path[1] == '/') {
        char *p;

        p = strchr(path + 2, '/');
        if (p) {
            p = strchr(p + 1, '/');
            if (p) {
                ofs = p + 1;
            }
        }
    }
    
    // check for drive path and skip N: part
    if (Q_charascii(*path) && path[1] == ':') {
        ofs = path + 2;
    }
#endif
```

**Comment by Paril** [comment]
No, I don't have any account restrictions. It seems to be an issue with `_mkdir`. The top part of that block seems to be addressing a similar bug under a different condition (you can't "mkdir" the share drive root).

**Comment by skullernet** [comment]
Apparently some Windows craziness is involved here. I get different results regarding whether `mkdir("c:")` returns EACCESS or EEXIST, depending on where I launch executable from.

Also `FS_CreatePath` would always fail if path has multiple slashes after drive part, e.g. `c:\\foo\bar` as it will attempt to `mkdir("c:\")`.

So yeah, the best approach is to skip the drive part.

**Comment by Paril** [comment]
Oh weird, cool, glad you narrowed it down! Thanks
