### ISSUE TITLE
[Feature] Lightgrid improvements

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#317]
I'm noting these down because I'll likely forget if I don't, and if nobody else has time after other stuff I'm working on is done I can look into these, but:

* lightgrid does not work with gl_shadows, because it doesn't store the trace plane when lightgrid is enabled
* trilinear interpolation; re-release will show the inputs and outputs via `r_showBSPLightGrid 1` + `stat quake.lightgrid`.

For reference purposes, here's pseudo-code that sort of kind of matches the implementation the re-release uses:
(I'm using the terminology that the format uses, so grid_size is the total bounds in units and grid_count is the number of points in the grid; in Q2PRO's code, I think it'd be `* grid_scale` and `grid_size` respectively.

EDIT: pseudocode removed

**Comment by skullernet** [comment]
I removed the pseudocode because it looks like slightly obfuscated real code to me. I don't know what origin of that code is, but to avoid any claims of infringing on third-party IP I removed it. I think that if needed, it is better to describe in words what the algorithm is doing.

**Comment by Paril** [comment]
> I removed the pseudocode because it looks like slightly obfuscated real code to me. I don't know what origin of that code is, but to avoid any claims of infringing on third-party IP I removed it. I think that if needed, it is better to describe in words what the algorithm is doing.

It was pseudo-code derived from code I had written for Quake II Re-release and described to others while working on the LIGHTGRID_OCTREE format for ericw-tools; I was told it was OK to pseudo-code-ify it to describe its behavior so it should be fine, especially since it's just math at the end of the day and it's basically what I had given to implementors while writing the code for ericw-tools anyways.

Essentially all it does is calculate the 2x2x2 square of colors around a given lightgrid point, ignoring the occluded samples and counting the total number of occluded ones; if any occlusions occur, a 'fill color' is calculated by aggregating the non-occluded samples together and averaging them. Any samples that were occluded are given this fill color. Then it's just trilinear at the end on the final array of 8 colors.

**Comment by skullernet** [comment]
Issue with `gl_shadows` has been fixed, and I've implemented lightgrid interpolation based on your description. Seems to work quite well.

**Comment by Paril** [comment]
Sweet! Looking forward to trying it out
