### ISSUE TITLE
translucent gun is drawn "below" alpha brush faces

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#323]
I ran into this while adding the muzzleflashes from Q2R; they use alpha texturing, so it relies on the draw order being correct, but the game currently draws the alpha world brushes after all translucent entities, causing water to disappear behind them.

This happens in Q2PRO as well - you can try it with a low `cl_gunalpha` and notice liquids and translucent surfaces disappear entirely.

My workaround currently is to draw entities in three steps - solids, `translucent but not weapon`, then the alpha world faces, and then `weapon`.

**Comment by skullernet** [comment]
Thanks, should be fixed now.
