### ISSUE TITLE
NAT Punchthrough

### ISSUE THREAD

**Issue by VinnyVicious** [skullernet/q2pro#332]
Playing online with friends right now is a bit convoluted and the easiest way out is using something like Hamachi. In FTEQW sv_public 2 uses TCP to connect to the master server instead of UDP, which allows the client and server to exchange address information.

https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/server/sv_main.c#l120

**Comment by skullernet** [comment]
No master server for Quake 2 supports this AFAIK, and implementing custom master server is out of scope of Q2PRO project. NAT punchthrough is outdated and unreliable technology, use IPv6 instead which eliminates NAT.
