### ISSUE TITLE
features to counter high ping players (100+)

### ISSUE THREAD

**Issue by VinnyVicious** [skullernet/q2pro#333]
For example:

- Client-side prediction
- "Unlagged"-style game code
- Preventing ice skating

**Comment by skullernet** [comment]
Changes to network code that impact game balance are not planned. Even adding variable server FPS support was a mistake in retrospect. Quake 2 is supposed to have lag due to interpolation and round trip times, learning to counteract that lag and predict your shots is part of the game.
