### ISSUE TITLE
Build failure on mingw: ld.lld: error: duplicate symbol: pthread_create

### ISSUE THREAD

**Issue by rorgoroth** [skullernet/q2pro#336]
Hello again,

I think this popped up a couple of weeks ago now out of nowhere, I couldn't see any commits that would cause it at the time, so I hacked around it to literally remove the duplicate and everything worked as expected but it should be fixed if possible and not an issue solely on my end.

Here attached are the configure and build logs.

[q2pro-configure.txt](https://github.com/skullernet/q2pro/files/13415877/q2pro-configure.txt)
[q2pro-build.txt](https://github.com/skullernet/q2pro/files/13415880/q2pro-build.txt)

Thanks for any help!

**Comment by skullernet** [comment]
```
error: duplicate symbol: pthread_create
>>> defined at ../src/windows/pthread.c
>>>            q2pro.exe.p/src_windows_pthread.c.obj
>>> defined at libpthread.a(libwinpthread_la-thread.o)
```

Something is causing `libwinpthread` being linked in your case, this shouldn't be happening. Q2PRO and all its dependencies have to be built with a compiler targeting Win32 threading model only.

At least with `gcc-mingw-w64` package in Debian, it comes in two flavors: one targeting POSIX threads (`-posix`) and one targeting Win32 threads (`-win32`). For building Q2PRO the one targeting Win32 threads must be used. It also must be used for building all dependencies.

**Comment by skullernet** [comment]
Added a workaround that should avoid duplicate symbols error, but you should really investigate why `libwinpthread` is being linked in the first place.

**Comment by rorgoroth** [comment]
Thanks, that works perfectly.

I'm currently working on my toolchain to try fix this, I'm half way there but building llvm/mingw over and over to test is rather time consuming.
