### ISSUE TITLE
Complete loss of sound if q2pro is renamed

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#341]
### Before reporting bugs

Built from my own fork as well as latest master branch from this repository

### Important information

Provide the following information:
- Q2PRO version
  - r3039~d7e4d98b
- OS version
  - Linux Mint 21
  - `Linux minty 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
```
- GPU driver and version
  -  `NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0`

### Reproduction steps

Build latest master branch, rename q2pro to q2pro1, open q2pro1, no menu sound or map sounds

### Expected behavior

Sound plays :)

### Actual behavior

Sound does not play

### Screenshots

If reporting graphics glitches, provide screenshot or video.

### Log file

Provide a link to the log file created by launching `q2pro +set developer 1
+set logfile 1`.

```
------- FS_Init -------
Current search path:
./baseq2
-----------------------
Logging console to logs/console.log
Execing config.cfg
GL_Init( 1 )
------- R_Init -------
Using video driver: x11
Found GLX_ARB_multisample
Found GLX_EXT_swap_control
Found GLX_EXT_swap_control_tear
Found GLX_ARB_create_context
Chosen FB config ID 0xa5
Chosen visual ID 0x21
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1080/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 525.125.06
GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
Detected OpenGL 4.6 (compatibility profile)
Loaded extension GL_ARB_fragment_program
Loaded extension GL_EXT_compiled_vertex_array
Using GLSL rendering backend.
----------------------
Registered 45 menus.
------- S_Init -------
Initializing OpenAL
Loaded extension ALC_EXT_EFX
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.19.1
Got 32 AL sources
OpenAL initialized.
----------------------
XInput2 mouse initialized
Supported cinematic formats: 0xf
Supported music formats: 0x1f
libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14 initialized.
====== Q2PRO initialized ======

q2pro r3039~d7e4d98b, Dec 19 2023
https://github.com/skullernet/q2pro

Compiled features: auto-reply avcodec client-gtv client-ui debug icmp-errors libcurl libjpeg libpng md3 md5 mvd-client mvd-server openal packetdup-hack save-games sdl2 software-sound system-console tga variable-fps x11 zlib
```
### Crash reports

If Q2PRO crashes, provide a crash report (Windows) or a backtrace (Linux). On
Linux, backtrace can be created by launching Q2PRO with `gdb q2pro --args
[...]` and typing `bt` after the crash.

**Comment by darkshade9** [comment]
I found what the problem was, but not why:

I regularly test out multiple builds of `q2pro` at once, to detect changes between branches and so forth.  Renaming `q2pro` to `q2pro1` or anything except `q2pro` will not play any sound, but rename it back to `q2pro` and it works again.  This is new, as I've generally always had a renamed executable to test side-by-side with stable master and have not encountered this issue before.

**Comment by skullernet** [comment]
As far as I'm aware, nothing has changed in Q2PRO that may have influenced this. Perhaps some PulseAudio/Pipewire "application profiles" are at play here? I don't use PulseAudio/Pipewire myself but I suspect these can use different configuration depending on process name.

**Comment by darkshade9** [comment]
Thanks, I will see if it's a Linux-specific thing.  Another member of the team was testing out the Windows build and sounds worked for him, except when playing back older MVDs; the footsteps sounds disappeared, so it's likely a separate issue.

**Comment by darkshade9** [comment]
Closing this as this may be a Linux-specific issue and I'm unable to test it on another system.
