### ISSUE TITLE
Building with USE_PROTOCOL_EXTENSIONS with legacy support?

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#344]
Hi,

Is it possible for builds to support the extended protocols, but to selectively enable it, so that legacy clients can still connect and play?

The ability to enable/disable within the gamelib, example:

https://github.com/skullernet/q2pro/blob/master/src/game/g_main.c#L173-L179

But `src/server/game.c` appears to be enabling this at the engine level, which causes `svs.csr.extended`, which in turn makes CLIENT_COMPATIBLE block protocol < 36

https://github.com/skullernet/q2pro/blob/master/src/server/game.c#L1000-L1003

https://github.com/skullernet/q2pro/blob/master/src/server/server.h#L181-L183

Unless I'm missing something, this breaks compatibility with older clients (maybe that is the intention?)

**Comment by skullernet** [comment]
> Is it possible for builds to support the extended protocols, but to selectively enable it, so that legacy clients can still connect and play?

A server/game built with `USE_PROTOCOL_EXTENSIONS` can support both normal and extended protocols. You can decide whether to export `GMF_PROTOCOL_EXTENSIONS` bit in `g_features` at game initialization time. If protocol extensions are enabled then legacy clients can't connect.

**Comment by darkshade9** [comment]
Thanks for the reply, here is what I am seeing:  Setting `g_protocol_extensions` to `0`:

![image](https://github.com/skullernet/q2pro/assets/1392336/666508cd-8b83-41b1-8250-d51616baf931)
extended == false

but then when the server initializes:

![image](https://github.com/skullernet/q2pro/assets/1392336/2233ef80-dcba-4289-92c5-8221ea12d720)

Some sort of race condition or something I'm missing?

**Comment by darkshade9** [comment]
I think I found the source of one of my issues (automatically enabling the `extended` bool), but now if I set `g_protocol_extensions` to `0`, I get a bad index on startup

```
------- Server Initialization -------
SpawnServer: zoo
********************
ERROR: PF_configstring: bad index: 12606
********************
==== ShutdownGame ====
********************
FATAL: Error during initialization: PF_configstring: bad index: 12606
********************
```

**Comment by skullernet** [comment]
It looks like you are just comparing values of `cs_remap_old` to `cs_remap_new` on the screenshot. Of course they will be different. What matters is what value `svs.csr` has after `SV_InitGameProgs()` returns.

If you get bad index error at startup it means server has not enabled extended protocol but your game library attempted to set extended configstring index. Check your code for why it happens.

**Comment by darkshade9** [comment]
Thanks, this helped me to look in the right direction.  I noticed that not all `MAX_EDICTS` / `MAX_EDICTS_OLD` had been changed over to `game.csr.max_edicts` (`g_phys.c` and `g_utils.c`), should I also be following that pattern?

**Comment by skullernet** [comment]
Perhaps? Fixed size arrays are simpler than allocating memory on heap, and VLAs are forbidden in Q2PRO codebase.
