### ISSUE TITLE
Map downloading from PAK file with allow_download_maps set to 1

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#345]
My Q2PRO dedicated server seems to be allowing clients to download map files from a PAK file over UDP, even with `allow_download_maps` set to 1.

These are the relevant settings in my server configuration:
```
set allow_download 1
set allow_download_maps 1
```

Version I am running is r3079

**Comment by ThePhatman** [comment]
Oh and I verified that the map file was not in the maps directory.
It was definitely coming from the PAK file.

**Comment by skullernet** [comment]
Logic to specially handle maps coming from PAK files has been removed quite a while ago in commit 205c61d. Looks like I forgot to update `allow_download_maps` documentation when removing it.

**Comment by ThePhatman** [comment]
And this behaviour is only for maps, as opposed to models?

**Comment by skullernet** [comment]
Only maps from PAK files have been handled specially before mentioned commit. After that commit, all `allow_download_*` cvars behave the same (accept either zero or non-zero).
