### ISSUE TITLE
MD5 scale bug

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#347]
Minor bug that was reported by a user to me directly; I applied the md5 joint scale at the wrong step, resulting in certain models (like CTF flags) looking weird.

EDIT: actually wait, this breaks death models. let me think a bit more about this...
EDIT 2: found it - I forgot to add support for the "scale_positions" key in md5scale. Working on it now, will send another patch when ready.
EDIT 3: okay, fixed. https://github.com/Paril/q2pro/commit/277192a6086beb7495ab61056a0381b44c44ae32

**Comment by skullernet** [comment]
Applied with some additional simplifications/fixes.

**Comment by Paril** [comment]
Cool ty. I haven't validated with your change yet, but basically just check that `monster_infantry`'s head pops off correctly, the Tesla weapon's viewmodel disappears correctly after being thrown, and that the CTF flag looks 'correct'. Those are all the three main use-cases for md5scale & cover all of the things I used them for.
