### ISSUE TITLE
Log console commands in the terminal

### ISSUE THREAD

**Issue by kke** [skullernet/q2pro#351]
The terminal log shows all the chat messages, events like who fragged who, server announcements and command responses, but not the commands entered in the console.

Several times I've tinkered with something in the console and found some setting / alias / command that I'd like to add to the config. It would be easy to copy-paste those from the log, but the log doesn't include any entered commands. As a workaround I can prefix the stuff with `echo`.

**Comment by kke** [comment]
Or maybe even better, add a `.history` file for persistent console history 🤔

**Comment by skullernet** [comment]
Right now entered commands are echoed, but only in place they are entered. If I understand the issue correctly, you want commands entered in graphical client console to be echoed in system terminal too? Seems reasonable.

There's support for persistent history in client console, but not system terminal. Maybe it can be added to system terminal too.

**Comment by kke** [comment]
Commands entered in the graphical game console do not appear in the terminal log, only the possible responses they generate.

I suppose many people won't see the terminal log anyway since they're not running q2pro from command line, so it's not probably something many people would even notice.

Aha, `con_history` needs to be set, the default is 0. I think that works for my needs.

**Comment by kke** [comment]
No need to waste any more time for something next to nobody notices and has a decent workaround
