### ISSUE TITLE
missing colormap.pcx

### ISSUE THREAD

**Issue by Franck6666** [skullernet/q2pro#352]
Hi, q2pro can't start up the game, giving this Error message instead. Note, in the same directory is yamagie installed and workx fine. 

./q2pro 
------- FS_Init -------
Current search path:
/home/franck/.q2pro/baseq2
/usr/local/share/q2pro/baseq2
-----------------------
------- R_Init -------
Using video driver: x11
Using GLSL rendering backend.
********************
FATAL: Couldn't load pics/colormap.pcx: No such file or directory
********************

ls -l

-rw-r--r-- 1 franck franck  142336 16 nov.   1997 3dfxgl.dll
drwx------ 2 franck franck    4096 21 juil.  2021 3zb2
drwx------ 2 franck franck    4096 21 juil.  2021 ace
drwx------ 2 franck franck    4096 21 juil.  2021 action
drwx------ 8 franck franck    4096 22 avril 23:28 baseq2
drwxr-xr-x 3 franck franck    4096  9 avril 15:48 build
drwx------ 2 franck franck    4096 30 déc.  01:15 chaos
drwx------ 2 franck franck    4096 21 juil.  2021 ctf
-rw-r--r-- 1 franck franck   21325 23 juin   2016 CWSDPMI.EXE
drwx------ 2 franck franck    4096 21 juil.  2021 dday
drwx------ 3 franck franck    4096 28 janv.  2021 docs
drwx------ 2 franck franck    4096 28 août   2021 DRIVERS
-rw-r--r-- 1 franck franck   13627 21 juil.  2021 gamespy.dxe
-rwxr-xr-x 1 franck franck 2048336 23 juin  17:50 gamex86_64.so
-rw-r--r-- 1 franck franck 1527724 21 juil.  2021 gl.dxe
-rw-r--r-- 1 franck franck      71 28 août   2021 infrun.bat
-rw-r--r-- 1 franck franck   21273 11 juin  06:16 LICENSE
-rw-r--r-- 1 franck franck   13350 29 nov.   1997 license.txt
-rw-r--r-- 1 franck franck   10651 11 juin  06:16 Makefile
drwx------ 5 franck franck    4096 23 juin   2016 opengl
-rw-r--r-- 1 franck franck  227328 25 nov.   1997 pvrgl.dll
-rwxr-xr-x 1 franck franck  341992 23 juin  16:51 q2ded
-rw-r--r-- 1 franck franck  834048 21 juil.  2021 q2.exe
-rw-r--r-- 1 franck franck     630 25 nov.   1997 q2.ico
-rwxr-xr-x 1 franck franck 4977536 23 juin  17:50 q2pro
-rwxr-xr-x 1 franck franck 1158352 23 juin  16:51 quake2
-rw-r--r-- 1 franck franck  291328 26 janv.  2021 quake2.exe
-rw-r--r-- 1 franck franck    9243 24 juin   2017 readme.fx
-rw-r--r-- 1 franck franck    4723 11 juin  06:16 README.md
-rw-r--r-- 1 franck franck    6954 24 juin   2017 readme.txt
-rwxr-xr-x 1 franck franck  419832 23 juin  16:51 ref_gl1.so
-rwxr-xr-x 1 franck franck  430104 23 juin  16:51 ref_gl3.so
-rw-r--r-- 1 franck franck  214528 30 nov.   1997 ref_gl.dll
-rw-r--r-- 1 franck franck  182228 21 juil.  2021 ref_gl.dxe
-rwxr-xr-x 1 franck franck  427288 23 juin  16:51 ref_gles3.so
-rw-r--r-- 1 franck franck  174592 30 nov.   1997 ref_soft.dll
-rw-r--r-- 1 franck franck  139622 21 juil.  2021 ref_soft.dxe
-rwxr-xr-x 1 franck franck  395768 23 juin  16:51 ref_soft.so
-rwxr-xr-x 1 franck franck  577792 11 juin  06:20 ref_vk.so
-rwxr-xr-x 1 franck franck  464328  9 avril 15:47 ref_vk.so.old
drwxr-xr-x 2 franck franck    4096  9 avril 15:48 release
drwx------ 2 franck franck    4096 21 juil.  2021 rogue
drwxr-xr-x 2 franck franck    4096  9 avril 15:48 shaders
-rw-r--r-- 1 franck franck   43364 21 juil.  2021 sndpci.dxe
drwxr-xr-x 7 franck franck    4096  9 avril 15:48 src
-rw-r--r-- 1 franck franck      10 23 mai    2021 start.bat
-rw-r--r-- 1 franck franck   33258 26 janv.  2021 Uninst.isu
drwx------ 7 franck franck    4096 23 juin   2016 voodoo
drwx------ 2 franck franck    4096 21 juil.  2021 xatrix
drwx------ 2 franck franck    4096 21 juil.  2021 zaero

**Comment by skullernet** [comment]
By default Q2PRO is built in ‘system-wide’ mode (unless building for Windows). In ‘system-wide’ mode current directory is not added to search paths. You can see the search paths it uses right at the beginning of the log. If you want to always launch Q2PRO from your Quake 2 directory, build it with `-Dsystem-wide=false`. In this mode Q2PRO will behave like traditional Quake 2 executable: read all files from current directory and also write files there. Regardless of how Q2PRO was built, you can also manually set `basedir`, `libdir` and `homedir` variables on command line.
