### ISSUE TITLE
[feature request] improved typing controls

### ISSUE THREAD

**Issue by 3hg4hj** [skullernet/q2pro#355]
for console and messagemode: ctrl-left and ctrl-right to move between words, ctrl-backspace and ctrl-delete to delete words left and right, adjustable typematic delay and rate [maybe consistent with win/X11 settings? would be better just as a cvar]

**Comment by skullernet** [comment]
> ctrl-left and ctrl-right to move between words

These might be supported, as they seem to work this way in bash/readline.

> ctrl-backspace and ctrl-delete to delete words left and right

What uses these bindings by default? Currently Ctrl+W erases word to the left of cursor.

> adjustable typematic delay and rate

These are already OS controlled on Windows and X11. Don't think Q2PRO really needs different settings from other GUI applications.

**Comment by 3hg4hj** [comment]
> These might be supported, as they seem to work this way in bash/readline.
nope!
> What uses these bindings by default? Currently Ctrl+W erases word to the left of cursor.
ezquake console, quake3e console, firefox, pretty much every conventional text editor [npp, kate, gedit, micro, lite xl]
> These are already OS controlled on Windows and X11. Don't think Q2PRO really needs different settings from other GUI applications.
oh, i guess you're right. something with gamescope
