### ISSUE TITLE
Replacement functionality for GL_ColorBytePointer and GL_VertexPointer

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#357]
Hello,

I'm getting around to syncing with the latest upstream changes and found an item I need a little assistance on.  I have a few custom functions that draw navmeshes on screen (for bot support).  These employed two, now deprecated, functions:

examples:
```
static const uint32_t colors[6] = {
        U32_RED, U32_RED,
        U32_GREEN, U32_GREEN,
        U32_BLUE, U32_BLUE
    };

    vec3_t points[6];

...

GL_ColorBytePointer(4, 0, (GLubyte *)colors);
GL_VertexPointer(3, 0, &points[0][0]);
```

Is there a direct replacement for these available?  There appear to have been a few iterations of changes around the `gl_backend` struct and I'm having a hard time reconciling the changes.

Thanks in advance

**Comment by skullernet** [comment]
Support for vertex arrays in client memory has been restricted to transparently support GL 3.2 core profile which doesn't allow client vertex arrays.

There's no longer support for separate vertex array for colors, colors must be interleaved with vertices in `tess.vertices` array. Then you call `GL_BindArrays` with one of the `VA_*` constants matching your vertex array layout. Finally you call `GL_LockArrays` to upload data to GL and then draw your geometry.

Look at `GL_DrawNullModel` for example of how to draw colored lines.

There's also new debug API support for drawing lines and text from within game code, maybe you can port your code to use that API if it is suitable.
