### ISSUE TITLE
Skuller.net is cybersquatted

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#358]
Your domain name, skuller.net seems to have fallen into the hands of cybersquatters.

**Comment by amokmen** [comment]
Nope. Just registrar did not get his money for another year )

There is 1 month time period (for different zones this time could vary), when owner could still pay and get domain functional again.

Only after that time someone else could lease (buy) this domain name for himself.

**Comment by skullernet** [comment]
Right, it's no longer feasible for me to continue paying for it, so I had to let it go. Q2PRO will only be represented on github from now on, you need to update your bookmarks.

**Comment by ThePhatman** [comment]
My apologies, I had not been aware that you had intended to take it down.

**Comment by UnknownUserMeMe** [comment]
> Right, it's no longer feasible for me to continue paying for it, so I had to let it go. Q2PRO will only be represented on github from now on, you need to update your bookmarks.

Andrey, hello. Your mail was on this domen (@skuller.net)
As far as I understand, when you refuse the domain, your email will change too? Can you suggest a new one?
