### ISSUE TITLE
Playground.ru issues

### ISSUE THREAD

**Issue by zhprzq2** [skullernet/q2pro#359]
Dear Skuller!
I'm here to represent Russian q2 community and ask u to kindly  help us in resetting admin password for q2.playground.ru servers that have been attacked lately.
For the last several years ive been one of the holders of the current ref password and been trying to keep this servers free from any misbehavior and political flamewar.
Now the password is somehow leaked and players are suffering from random ban at all the server ports constantly.
We have a trusted group of well known players that will continue administrating our beloved server and we know no other person to help us but you!
Respectfully yours ru q2!

**Comment by zhprzq2** [comment]
For the nonce out team is struggling in unbanning players manually, a lot of requests are coming from the mobile connections and via telegram.

**Comment by vic7or777** [comment]
Need example of <ip/**mask**> for command "unban" at openffa mod.
No one type of mask didn't work

**Comment by skullernet** [comment]
Why can't regular Playground.ru staff do anything about this? Since my SSH access still seems to work, I've removed admin password on all ports. But please direct such requests to Playground.ru staff in the future. Issues like this are off-topic here.
