### ISSUE TITLE
Skybox filtering toggle 

### ISSUE THREAD

**Issue by Alevam-Inc** [skullernet/q2pro#372]
Add the ability to toggle between nearest and bilinear texture filtering for the skybox.

**Comment by skullernet** [comment]
Already [exists](https://github.com/skullernet/q2pro/blob/cd3f69e66b83931c2c34841099784fb0e91d7dad/doc/client.asciidoc?plain=1#L664).

**Comment by Alevam-Inc** [comment]
Okay then, I guess I should have looked for the word “skies” instead of just “sky”.
