### ISSUE TITLE
Switching between clients creates an incompatible config.cfg 

### ISSUE THREAD

**Issue by kke** [skullernet/q2pro#373]
I'd like the configuration auto-save to update something like `q2pro.cfg` instead of `config.cfg`. Now when switching between different clients, each write their config over `config.cfg` on quit or when changing settings and it breaks it for the other clients as they contain incompatible settings. When starting up, the `q2pro.cfg` would then be preferred over loading `config.cfg`.

I made the same issue on https://github.com/yquake2/yquake2/issues/1165

**Comment by skullernet** [comment]
You should not let different clients share single home directory (unless you use Windows). On Unix-like OSes Q2PRO writes data to `~/.q2pro` directory by default, so it shouldn't clash with any other client. On Windows, where standard practice is to run multiple clients from single directiory, Q2PRO writes config to `q2config.cfg` to avoid clashing with other clients. You can change default config file name for Unix-like OSes too in `inc/common/common.h`.

**Comment by kke** [comment]
Then the same maps etc are downloaded multiple times unless you get creative with symlinks.

**Comment by kke** [comment]
Closed in yamagi so let's just agree it's not a good idea.
