### ISSUE TITLE
Start using SDL2

### ISSUE THREAD

**Issue by hifi** [skullernet/q2pro#66]
This is not so important as mainstream distributions (notably Ubuntu) have not yet shipped it.

However, it has one interesting and important feature, raw input. It's more useful than using raw devices directly as it works without any permission hacks. I've been very happy with how Valve exposed raw input on Linux using SDL2.

The changes to SDL code seem to be big enough it would promote a new sdl2 backend in src/unix/ and USE_SDL2 flag. Once SDL2 support matures in distributions dropping legacy SDL would be possible. At this rate it seems the turnaround would be from 6 to 12 months for Ubuntu based distributions. For Debian jessie it will be much longer though. Fedora already ships SDL2.

**Comment by skullernet** [comment]
SDL2 has been the only option to build with since b6d6253756c1525a4e074453299be563820b27d6.
