### ISSUE TITLE
vid_modelist exceeding 1024 chars

### ISSUE THREAD

**Issue by ghost** [skullernet/q2pro#76]
I received a report from a user where the 'video mode' menu item was missing, so I had him do: echo $vid_modelist and this was the result:

 Expanded line exceeded 1024 chars, discarded.

It seems this limit may need to be increased after the recent change to separately list refresh rates for each resolution.

**Comment by skullernet** [comment]
A workaround for displaying large lists (> 1024 chars) in UI has been added. Macro expansion in console is still limited to 1024 chars though.
