### ISSUE TITLE
Shadows under Strogg flag model 

### ISSUE THREAD

**Issue by ghost** [skullernet/q2pro#85]
I noticed this recently when playing single player mode and it looked pretty unnatural / out of place; I think it would be better to disable drawing shadows for this model.

![strogg-flag-shadow](https://f.cloud.github.com/assets/1663929/1558804/6209d03c-4fad-11e3-8fc5-39a8a756648b.jpg)

**Comment by skullernet** [comment]
Done in c1c2d8d88d9fa790ab24c5e2d0c89a651485a957. It will only work when using Q2PRO baseq2 game library.
