### ISSUE TITLE
MVD Client not enabled by default

### ISSUE THREAD

**Issue by joe0x04** [skullernet/q2pro#95]
I was pulling my hair out for a while trying to figure out why new versions of Q2Pro weren't listening for MVD connections. Not until I tried setting up a new GTV server did I figure out both MVD client and server functionality is disabled by default and can only be enabled by defining CONFIG_MVD_\* and recompiling. 

I guess this works for the server, but please enable MVD client functionality by default. It would be infinitely easier to setup GTV servers without having to ask absent, unreachable or in some cases completely clueless admins to recompile their software. 

It would greatly help with things like EDL and other leagues that draw big numbers of people to see high-profile matches.

Thanks for the awesome software btw :)
/claire

**Comment by skullernet** [comment]
MVD client and server are enabled by default when building with Meson, which is preferred method to build Q2PRO now.
