### ISSUE TITLE
Small changes from Q2PRO "plus"

### ISSUE THREAD

**Issue by hifi** [skullernet/q2pro#96]
Since you're not dead anymore, can you cherry pick the other changes from my repo other than #91 so I can stop maintaining the fork?

https://github.com/hifi/q2pro/commits/plus

**Comment by skullernet** [comment]
* I'll reply about SV_ConsoleOutput() in its own issue.

* `ch_scale` being specified relative to `scr_scale` is a feature. It makes crosshair size automatically scale with display resolution. If you consider crosshair size to be too big, you can use values less than 1 for `ch_scale`.

* Removing `cl_maxfps` limit is not acceptable. Clients should not be allowed to flood the server with 1000 packets/sec.

* Action mod scope scaling has been implemented in b708a2f9.

**Comment by hifi** [comment]
Wow, eight years, though cool you came around  :+1:. I think the mod scope scaling was the only real issue in the end as it felt very broken without the hack.

Thanks!
